use anyhow::Result;
use serde::Deserialize;
use std::collections::BTreeMap;

#[derive(Deserialize)]
struct SchemaField {
    #[serde(rename = "type")]
    field_type: String,
    required: bool,
}

#[derive(Deserialize)]
struct Schema {
    enums: BTreeMap<String, Vec<String>>,
    types: BTreeMap<String, BTreeMap<String, SchemaField>>,
    components: BTreeMap<String, BTreeMap<String, SchemaField>>,
}

fn load_schema() -> Schema {
    serde_json::from_str(include_str!("../schema/components.json")).expect("invalid schema JSON")
}

pub fn emit_typescript() -> Result<()> {
    print!("{}", generate_typescript());
    Ok(())
}

fn component_defs() -> Vec<(&'static str, Vec<(&'static str, &'static str)>)> {
    let schema = load_schema();
    schema
        .components
        .into_iter()
        .map(|(tag, fields)| {
            let tag: &'static str = Box::leak(tag.into_boxed_str());
            let fields: Vec<(&'static str, &'static str)> = fields
                .into_iter()
                .map(|(name, field)| {
                    let name_str = if field.required {
                        name
                    } else {
                        format!("{}?", name)
                    };
                    let name: &'static str = Box::leak(name_str.into_boxed_str());
                    let ftype: &'static str = Box::leak(field.field_type.into_boxed_str());
                    (name, ftype)
                })
                .collect();
            (tag, fields)
        })
        .collect()
}

fn generate_typescript() -> String {
    let mut out = String::with_capacity(8192);
    out.push_str("// Auto-generated by `kazam sdk emit` — do not edit\n\n");

    let schema = load_schema();

    // Enums from schema
    for (name, variants) in &schema.enums {
        let variant_refs: Vec<&str> = variants.iter().map(|s| s.as_str()).collect();
        emit_enum(&mut out, name, &variant_refs);
    }

    // Supporting types from schema
    for (name, fields) in &schema.types {
        // Build field list in the format emit_interface expects: ("name" or "name?", "type")
        let field_list: Vec<(String, String)> = fields
            .iter()
            .map(|(fname, field)| {
                let key = if field.required {
                    fname.clone()
                } else {
                    format!("{}?", fname)
                };
                (key, field.field_type.clone())
            })
            .collect();
        let field_refs: Vec<(&str, &str)> = field_list
            .iter()
            .map(|(k, v)| (k.as_str(), v.as_str()))
            .collect();
        emit_interface(&mut out, name, &field_refs);
    }

    // Slide type (not in schema, stays hardcoded)
    emit_interface(
        &mut out,
        "Slide",
        &[
            ("label", "string"),
            ("components", "Component[]"),
            ("hide_label?", "boolean"),
        ],
    );

    // Component union (tagged by "type")
    out.push_str("export type Component =\n");
    let components = component_defs();

    for (i, (tag, fields)) in components.iter().enumerate() {
        out.push_str("  | { type: \"");
        out.push_str(tag);
        out.push('"');
        for (name, ts_type) in fields {
            out.push_str("; ");
            out.push_str(name);
            out.push_str(": ");
            out.push_str(ts_type);
        }
        out.push_str(" }");
        if i < components.len() - 1 {
            out.push('\n');
        }
    }
    out.push_str(";\n\n");

    // Freshness types
    emit_interface(
        &mut out,
        "SourceOfTruth",
        &[("label", "string"), ("href?", "string")],
    );
    emit_interface(
        &mut out,
        "RefreshStep",
        &[
            ("run?", "string"),
            ("prompt?", "string"),
            ("review?", "string"),
        ],
    );
    emit_interface(
        &mut out,
        "RefreshConfig",
        &[("mode?", "RefreshMode"), ("steps?", "RefreshStep[]")],
    );
    emit_interface(
        &mut out,
        "Freshness",
        &[
            ("updated?", "string"),
            ("review_every?", "string"),
            ("owner?", "string"),
            ("sources_of_truth?", "(string | SourceOfTruth)[]"),
            ("expires?", "string"),
            ("refresh?", "string | RefreshConfig"),
        ],
    );
    emit_interface(
        &mut out,
        "Reference",
        &[("url", "string"), ("note?", "string")],
    );

    // Nav / Site config
    emit_interface(
        &mut out,
        "NavLink",
        &[
            ("label", "string"),
            ("href?", "string"),
            ("children?", "NavLink[]"),
            ("personas?", "string[]"),
            ("collapsed?", "boolean"),
        ],
    );
    emit_interface(
        &mut out,
        "Voice",
        &[
            ("tone?", "string"),
            ("reading_level?", "string"),
            (
                "terminology?",
                "{ prefer?: Record<string, string>; avoid?: string[] }",
            ),
        ],
    );
    emit_interface(
        &mut out,
        "Role",
        &[
            ("id", "string"),
            ("label", "string"),
            ("description?", "string"),
            ("icon?", "string"),
            ("href?", "string"),
        ],
    );
    emit_interface(
        &mut out,
        "DriftRepo",
        &[("prefix", "string"), ("local?", "string")],
    );
    emit_interface(&mut out, "DriftConfig", &[("repos", "DriftRepo[]")]);

    // Page
    out.push_str("export interface Page {\n");
    out.push_str("  title: string;\n");
    out.push_str("  shell: Shell;\n");
    out.push_str("  eyebrow?: string;\n");
    out.push_str("  subtitle?: string;\n");
    out.push_str("  components?: Component[];\n");
    out.push_str("  slides?: Slide[];\n");
    out.push_str("  unlisted?: boolean;\n");
    out.push_str("  texture?: Texture;\n");
    out.push_str("  glow?: Glow;\n");
    out.push_str("  print_flow?: PrintFlow;\n");
    out.push_str("  search_terms?: string[];\n");
    out.push_str("  freshness?: \"never\" | Freshness;\n");
    out.push_str("  owner?: string;\n");
    out.push_str("  references?: Reference[];\n");
    out.push_str("  personas?: string[];\n");
    out.push_str("  archived?: boolean;\n");
    out.push_str("  draft?: boolean;\n");
    out.push_str("  nav_layout?: NavLayout;\n");
    out.push_str("  nav?: NavLink[];\n");
    out.push_str("}\n\n");

    // SiteConfig
    out.push_str("export interface SiteConfig {\n");
    out.push_str("  name: string;\n");
    out.push_str("  theme?: string;\n");
    out.push_str("  colors?: Record<string, string>;\n");
    out.push_str("  nav?: NavLink[];\n");
    out.push_str("  favicon?: string | { svg?: string; png?: string; ico?: string; apple_touch_icon?: string };\n");
    out.push_str("  logo?: string | { src: string; height?: string; alt?: string };\n");
    out.push_str("  view_source?: boolean;\n");
    out.push_str("  texture?: Texture;\n");
    out.push_str("  glow?: Glow;\n");
    out.push_str("  nav_layout?: NavLayout;\n");
    out.push_str("  mode?: Mode;\n");
    out.push_str("  description?: string;\n");
    out.push_str("  url?: string;\n");
    out.push_str("  edit_url?: string;\n");
    out.push_str("  og_image?: string;\n");
    out.push_str("  voice?: Voice;\n");
    out.push_str("  roles?: Role[];\n");
    out.push_str("  drift?: DriftConfig;\n");
    out.push_str("}\n\n");

    // ValidationError
    emit_interface(
        &mut out,
        "ValidationError",
        &[
            ("file", "string"),
            ("path", "string"),
            ("error_type", "string"),
            ("message", "string"),
            ("suggestion?", "string"),
        ],
    );

    // Annotation
    emit_interface(
        &mut out,
        "Annotation",
        &[
            ("id", "string"),
            ("text", "string"),
            ("author", "string"),
            ("section?", "string"),
            ("added", "string"),
            ("status", "AnnotationStatus"),
            ("source", "AnnotationSource"),
        ],
    );

    out
}

pub fn emit_react() -> Result<()> {
    print!("{}", generate_react());
    Ok(())
}

pub fn emit_schema() -> Result<()> {
    print!("{}", generate_schema());
    Ok(())
}

fn generate_schema() -> String {
    // The schema file IS the source of truth — just re-emit it as canonical JSON.
    let schema = load_schema();

    let mut out = String::with_capacity(16384);
    out.push_str("{\n");

    // Enums
    let enums: Vec<(&String, &Vec<String>)> = schema.enums.iter().collect();
    out.push_str("  \"enums\": {\n");
    for (i, (name, variants)) in enums.iter().enumerate() {
        out.push_str("    \"");
        out.push_str(name);
        out.push_str("\": [");
        for (j, v) in variants.iter().enumerate() {
            if j > 0 {
                out.push_str(", ");
            }
            out.push('"');
            out.push_str(v);
            out.push('"');
        }
        out.push(']');
        if i < enums.len() - 1 {
            out.push(',');
        }
        out.push('\n');
    }
    out.push_str("  },\n");

    // Types
    let types: Vec<(&String, &BTreeMap<String, SchemaField>)> = schema.types.iter().collect();
    out.push_str("  \"types\": {\n");
    for (i, (name, fields)) in types.iter().enumerate() {
        out.push_str("    \"");
        out.push_str(name);
        out.push_str("\": {\n");
        let field_list: Vec<(&String, &SchemaField)> = fields.iter().collect();
        for (j, (fname, field)) in field_list.iter().enumerate() {
            out.push_str("      \"");
            out.push_str(fname);
            out.push_str("\": { \"type\": \"");
            out.push_str(&field.field_type);
            out.push_str("\", \"required\": ");
            out.push_str(if field.required { "true" } else { "false" });
            out.push_str(" }");
            if j < field_list.len() - 1 {
                out.push(',');
            }
            out.push('\n');
        }
        out.push_str("    }");
        if i < types.len() - 1 {
            out.push(',');
        }
        out.push('\n');
    }
    out.push_str("  },\n");

    // Components
    let components_map: Vec<(&String, &BTreeMap<String, SchemaField>)> =
        schema.components.iter().collect();
    out.push_str("  \"components\": {\n");
    for (i, (tag, fields)) in components_map.iter().enumerate() {
        out.push_str("    \"");
        out.push_str(tag);
        out.push_str("\": {\n");
        let field_list: Vec<(&String, &SchemaField)> = fields.iter().collect();
        for (j, (fname, field)) in field_list.iter().enumerate() {
            out.push_str("      \"");
            out.push_str(fname);
            out.push_str("\": { \"type\": \"");
            out.push_str(&field.field_type);
            out.push_str("\", \"required\": ");
            out.push_str(if field.required { "true" } else { "false" });
            out.push_str(" }");
            if j < field_list.len() - 1 {
                out.push(',');
            }
            out.push('\n');
        }
        out.push_str("    }");
        if i < components_map.len() - 1 {
            out.push(',');
        }
        out.push('\n');
    }
    out.push_str("  }\n");

    out.push_str("}\n");
    out
}

pub fn emit_agents() -> Result<()> {
    print!("{}", generate_agents());
    Ok(())
}

fn yaml_example_value(field_type: &str, field_name: &str, schema: &Schema) -> String {
    if field_type.ends_with("[]") {
        return "[]".to_string();
    }
    match field_type {
        "string" => match field_name {
            "title" | "heading" | "label" | "term" => "\"Example Title\"",
            "body" | "description" | "detail" | "definition" | "summary" => "\"Description text\"",
            "value" => "\"$1.2M\"",
            "href" | "src" | "link" | "url" => "\"https://example.com\"",
            "code" => "\"console.log('hello')\"",
            "language" => "\"typescript\"",
            "key" => "\"metric\"",
            "name" => "\"Example\"",
            "date" => "\"2025-01-15\"",
            "alt" | "caption" => "\"Image description\"",
            "aspect" => "\"16:9\"",
            _ => "\"example\"",
        }
        .to_string(),
        "number" => match field_name {
            "value" => "42",
            "columns" | "max" | "limit" | "min_width" => "3",
            "height" | "max_width" => "300",
            _ => "0",
        }
        .to_string(),
        "boolean" => "false".to_string(),
        _ => {
            if let Some(variants) = schema.enums.get(field_type) {
                if let Some(first) = variants.first() {
                    return format!("\"{}\"", first);
                }
            }
            "{}".to_string()
        }
    }
}

fn generate_agents() -> String {
    let schema = load_schema();
    let mut out = String::with_capacity(32768);

    out.push_str("# kazam component reference\n\n");
    out.push_str("Auto-generated from schema. Do not edit.\n\n");

    // Enums
    out.push_str("## Enums\n\n");
    for (name, variants) in &schema.enums {
        out.push_str("### ");
        out.push_str(name);
        out.push('\n');
        out.push_str("Values: ");
        for (i, v) in variants.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push('`');
            out.push_str(v);
            out.push('`');
        }
        out.push_str("\n\n");
    }

    // Types
    out.push_str("## Types\n\n");
    for (name, fields) in &schema.types {
        out.push_str("### ");
        out.push_str(name);
        out.push('\n');
        out.push_str("| Field | Type | Required |\n");
        out.push_str("|-------|------|----------|\n");
        for (fname, field) in fields {
            out.push_str("| ");
            out.push_str(fname);
            out.push_str(" | ");
            out.push_str(&field.field_type);
            out.push_str(" | ");
            out.push_str(if field.required { "yes" } else { "no" });
            out.push_str(" |\n");
        }
        out.push('\n');
    }

    // Components
    out.push_str("## Components\n\n");
    for (tag, fields) in &schema.components {
        out.push_str("### ");
        out.push_str(tag);
        out.push('\n');
        out.push_str("| Field | Type | Required |\n");
        out.push_str("|-------|------|----------|\n");
        for (fname, field) in fields {
            out.push_str("| ");
            out.push_str(fname);
            out.push_str(" | ");
            out.push_str(&field.field_type);
            out.push_str(" | ");
            out.push_str(if field.required { "yes" } else { "no" });
            out.push_str(" |\n");
        }
        out.push('\n');

        // YAML example: required fields + up to 2 optional
        out.push_str("```yaml\n");
        out.push_str("- type: ");
        out.push_str(tag);
        out.push('\n');
        let mut optional_shown = 0usize;
        for (fname, field) in fields {
            if field.required {
                out.push_str("  ");
                out.push_str(fname);
                out.push_str(": ");
                out.push_str(&yaml_example_value(&field.field_type, fname, &schema));
                out.push('\n');
            } else if optional_shown < 2 {
                out.push_str("  ");
                out.push_str(fname);
                out.push_str(": ");
                out.push_str(&yaml_example_value(&field.field_type, fname, &schema));
                out.push_str("  # optional\n");
                optional_shown += 1;
            }
        }
        out.push_str("```\n\n");
    }

    out
}

fn generate_react() -> String {
    let mut out = String::with_capacity(65536);
    out.push_str(RENDERER_RAW);
    generate_editor(&mut out);
    out
}

const RENDERER_RAW: &str = r####""use client";
// Auto-generated by `kazam sdk emit-react` — do not edit
/* eslint-disable @next/next/no-img-element */
import React from "react";
import { stringify as yamlStringify, parse as yamlParse } from "yaml";

interface SlideData {
  label: string;
  components?: ComponentData[];
  hide_label?: boolean;
  cover?: boolean;
}

interface FreshnessData {
  updated?: string;
  review_every?: string;
  owner?: string;
  expires?: string;
}

interface PageData {
  title: string;
  subtitle?: string;
  shell?: string;
  components?: ComponentData[];
  slides?: SlideData[];
  freshness?: FreshnessData | "never";
}

interface ComponentData {
  type: string;
  [key: string]: unknown;
}

interface PageRendererProps {
  page: PageData;
  renderMarkdown?: (md: string) => string;
  renderChart?: (comp: ComponentData) => React.ReactNode;
  renderRoleMap?: (comp: ComponentData) => React.ReactNode;
}

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

const _assetBase = typeof process !== "undefined" && process.env?.NEXT_PUBLIC_BASE_PATH || "";
function assetSrc(src: string): string {
  if (_assetBase && src.startsWith("/") && !src.startsWith("//")) return _assetBase + src;
  return src;
}

function renderInline(text: string): React.ReactNode[] {
  const pattern = /(`[^`]+`|\*\*[^*]+\*\*|\*[^*]+\*|\[[^\]]+\]\([^)]+\))/g;
  const parts: React.ReactNode[] = [];
  let last = 0;
  let match: RegExpExecArray | null;
  let key = 0;
  while ((match = pattern.exec(text)) !== null) {
    if (match.index > last) parts.push(text.slice(last, match.index));
    const token = match[0];
    if (token.startsWith("`")) {
      parts.push(<code key={key++} className="c-inline-code">{token.slice(1, -1)}</code>);
    } else if (token.startsWith("**")) {
      parts.push(<strong key={key++}>{token.slice(2, -2)}</strong>);
    } else if (token.startsWith("[")) {
      const labelEnd = token.indexOf("](");
      const label = token.slice(1, labelEnd);
      const href = token.slice(labelEnd + 2, -1);
      parts.push(<a key={key++} href={href}>{label}</a>);
    } else {
      parts.push(<em key={key++}>{token.slice(1, -1)}</em>);
    }
    last = match.index + token.length;
  }
  if (last < text.length) parts.push(text.slice(last));
  return parts;
}

function renderBlock(text: string): React.ReactElement {
  const lines = text.split("\n");
  const elements: React.ReactNode[] = [];
  let key = 0;
  let listItems: React.ReactNode[] = [];
  let listTag: "ul" | "ol" = "ul";

  const flushList = () => {
    if (listItems.length > 0) {
      const List = listTag;
      elements.push(<List key={key++} className="c-md-list">{listItems}</List>);
      listItems = [];
    }
  };

  for (const line of lines) {
    const trimmed = line.trimStart();
    if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
      if (listTag !== "ul") flushList();
      listTag = "ul";
      listItems.push(<li key={key++}>{renderInline(trimmed.slice(2))}</li>);
    } else if (/^\d+\.\s/.test(trimmed)) {
      if (listTag !== "ol") flushList();
      listTag = "ol";
      listItems.push(<li key={key++}>{renderInline(trimmed.replace(/^\d+\.\s/, ""))}</li>);
    } else if (trimmed === "") {
      flushList();
    } else if (trimmed.startsWith("### ")) {
      flushList();
      elements.push(<h3 key={key++}>{renderInline(trimmed.slice(4))}</h3>);
    } else if (trimmed.startsWith("## ")) {
      flushList();
      elements.push(<h2 key={key++}>{renderInline(trimmed.slice(3))}</h2>);
    } else if (trimmed.startsWith("# ")) {
      flushList();
      elements.push(<h1 key={key++}>{renderInline(trimmed.slice(2))}</h1>);
    } else if (/^!\[.*\]\(.*\)$/.test(trimmed)) {
      flushList();
      const alt = trimmed.slice(2, trimmed.indexOf("]("));
      const src = trimmed.slice(trimmed.indexOf("](") + 2, -1);
      elements.push(<img key={key++} src={assetSrc(src)} alt={alt} />);
    } else if (trimmed === "---" || trimmed === "***" || trimmed === "___") {
      flushList();
      elements.push(<hr key={key++} />);
    } else {
      flushList();
      elements.push(<p key={key++}>{renderInline(trimmed)}</p>);
    }
  }
  flushList();
  return <>{elements}</>;
}

function ChartSVG({ id, comp }: { id?: string; comp: ComponentData }) {
  const [tip, setTip] = React.useState<{ x: number; y: number; text: string } | null>(null);
  const title = comp.title as string | undefined;
  const kind = (comp.kind as string) || "bar";
  const data = (comp.data as Array<{ label: string; value: number; color?: string }>) || [];
  const series = (comp.series as Array<{ label: string; color?: string; points: Array<{ label: string; value: number }> }>) || [];
  const h = (comp.height as number) || 200;
  const orientation = (comp.orientation as string) || "vertical";

  const semToHex: Record<string, string> = { default: "var(--color-text-muted, #999)", green: "var(--color-green, #4ade80)", yellow: "var(--color-yellow, #facc15)", red: "var(--color-red, #f87171)", teal: "var(--color-teal, #2dd4bf)" };
  const getColor = (c?: string, i?: number) => {
    if (c && semToHex[c]) return semToHex[c];
    const palette = ["var(--color-accent, #8b5cf6)", "var(--color-green, #4ade80)", "var(--color-yellow, #facc15)", "var(--color-red, #f87171)", "var(--color-teal, #2dd4bf)"];
    return palette[(i || 0) % palette.length];
  };

  const Tip = tip ? (
    <g pointerEvents="none">
      <rect x={tip.x - tip.text.length * 3.5 - 6} y={tip.y - 24} width={tip.text.length * 7 + 12} height={20} rx={4} fill="var(--color-bg, #111)" stroke="var(--color-text-muted, #666)" strokeWidth="0.5" opacity="0.95" />
      <text x={tip.x} y={tip.y - 11} textAnchor="middle" fontSize={11} fontWeight="600" fill="var(--color-text, #eee)">{tip.text}</text>
    </g>
  ) : null;

  let chart: React.ReactNode = null;

  if (kind === "pie" && data.length > 0) {
    const total = data.reduce((s, d) => s + d.value, 0);
    const cx = 80, cy = 80, r = 70;
    let cumAngle = -Math.PI / 2;
    const slices = data.map((d, i) => {
      const angle = (d.value / total) * 2 * Math.PI;
      const x1 = cx + r * Math.cos(cumAngle);
      const y1 = cy + r * Math.sin(cumAngle);
      const midAngle = cumAngle + angle / 2;
      cumAngle += angle;
      const x2 = cx + r * Math.cos(cumAngle);
      const y2 = cy + r * Math.sin(cumAngle);
      const large = angle > Math.PI ? 1 : 0;
      const path = `M${cx},${cy} L${x1},${y1} A${r},${r} 0 ${large} 1 ${x2},${y2} Z`;
      const pct = Math.round((d.value / total) * 100);
      const tx = cx + (r * 0.6) * Math.cos(midAngle);
      const ty = cy + (r * 0.6) * Math.sin(midAngle);
      return <path key={i} d={path} fill={getColor(d.color, i)} stroke="var(--color-bg, #111)" strokeWidth="1" className="c-chart-slice" onMouseEnter={() => setTip({ x: tx, y: ty, text: `${d.label}: ${d.value} (${pct}%)` })} onMouseLeave={() => setTip(null)} />;
    });
    const legend = data.map((d, i) => (
      <div key={i} style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 12 }}>
        <span style={{ width: 10, height: 10, borderRadius: "50%", background: getColor(d.color, i), display: "inline-block" }} />
        <span>{d.label}: {d.value}</span>
      </div>
    ));
    chart = (
      <div style={{ display: "flex", alignItems: "center", gap: 24, justifyContent: "center" }}>
        <svg viewBox="0 0 160 160" style={{ width: "40%", maxWidth: 200, minWidth: 120, flexShrink: 0, overflow: "visible" }}>{slices}{Tip}</svg>
        <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>{legend}</div>
      </div>
    );
  } else if (kind === "bar" && data.length > 0) {
    const maxVal = Math.max(...data.map(d => d.value), 1);
    const vw = 600;
    const padX = 40;
    const padTop = 28;
    const gap = 8;
    const barW = Math.max(20, (vw - padX * 2 - gap * (data.length - 1)) / data.length);
    if (orientation === "horizontal") {
      const barH = 24;
      const svgH = data.length * (barH + 6) + 20;
      chart = (
        <svg width="100%" viewBox={`0 0 ${vw} ${svgH}`} preserveAspectRatio="xMidYMid meet" style={{ overflow: "visible" }}>
          {data.map((d, i) => {
            const w = (d.value / maxVal) * (vw - 120);
            const y = i * (barH + 6) + 10;
            return <React.Fragment key={i}>
              <rect x={80} y={y} width={w} height={barH} fill={getColor(d.color, i)} rx={3} className="c-chart-bar" onMouseEnter={() => setTip({ x: 80 + w / 2, y: y - 4, text: `${d.label}: ${d.value}` })} onMouseLeave={() => setTip(null)} />
              <text x={74} y={y + barH / 2 + 4} textAnchor="end" fontSize={11} fill="var(--color-text-muted, #999)">{d.label}</text>
              <text x={84 + w} y={y + barH / 2 + 4} fontSize={11} fill="var(--color-text-muted, #999)">{d.value}</text>
            </React.Fragment>;
          })}
          {Tip}
        </svg>
      );
    } else {
      const plotH = h - padTop;
      chart = (
        <svg width="100%" viewBox={`0 0 ${vw} ${h + 30}`} preserveAspectRatio="xMidYMid meet" style={{ overflow: "visible" }}>
          <line x1={padX} y1={h} x2={vw - padX} y2={h} stroke="var(--color-text-muted, #999)" strokeWidth="0.5" strokeOpacity="0.3" />
          {data.map((d, i) => {
            const barH = (d.value / maxVal) * plotH;
            const x = padX + i * (barW + gap);
            return <React.Fragment key={i}>
              <rect x={x} y={h - barH} width={barW} height={barH} fill={getColor(d.color, i)} rx={3} className="c-chart-bar" onMouseEnter={() => setTip({ x: x + barW / 2, y: h - barH - 4, text: `${d.label}: ${d.value}` })} onMouseLeave={() => setTip(null)} />
              <text x={x + barW / 2} y={h - barH - 6} textAnchor="middle" fontSize={11} fontWeight="500" fill="var(--color-text, #eee)">{d.value}</text>
              <text x={x + barW / 2} y={h + 16} textAnchor="middle" fontSize={11} fill="var(--color-text-muted, #999)">{d.label}</text>
            </React.Fragment>;
          })}
          {Tip}
        </svg>
      );
    }
  } else if (kind === "timeseries" && series.length > 0) {
    const allPoints = series.flatMap(s => s.points);
    const maxVal = Math.max(...allPoints.map(p => p.value), 1);
    const vw = 600;
    const pad = { l: 50, r: 20, t: 20, b: 24 };
    const plotW = vw - pad.l - pad.r;
    const plotH = h - pad.t - pad.b;
    const n = series[0]?.points.length || 1;
    const gridLines = [0, 0.25, 0.5, 0.75, 1].map((frac, gi) => {
      const y = pad.t + plotH * (1 - frac);
      const val = Math.round(maxVal * frac);
      return <React.Fragment key={gi}>
        <line x1={pad.l} y1={y} x2={vw - pad.r} y2={y} stroke="var(--color-text-muted, #999)" strokeWidth="0.5" strokeOpacity="0.2" />
        <text x={pad.l - 6} y={y + 4} textAnchor="end" fontSize={10} fill="var(--color-text-muted, #999)">{val}</text>
      </React.Fragment>;
    });
    const lines = series.map((s, si) => {
      const pts = s.points.map((p, pi) => {
        const x = pad.l + (pi / Math.max(n - 1, 1)) * plotW;
        const y = pad.t + plotH - (p.value / maxVal) * plotH;
        return `${x},${y}`;
      }).join(" ");
      return <polyline key={si} points={pts} fill="none" stroke={getColor(s.color, si)} strokeWidth="2.5" strokeLinejoin="round" />;
    });
    const dots = series.map((s, si) =>
      s.points.map((p, pi) => {
        const x = pad.l + (pi / Math.max(n - 1, 1)) * plotW;
        const y = pad.t + plotH - (p.value / maxVal) * plotH;
        const label = series.length > 1 ? `${s.label}: ${p.value}` : String(p.value);
        return <circle key={`${si}-${pi}`} cx={x} cy={y} r={4} fill={getColor(s.color, si)} className="c-chart-dot" onMouseEnter={() => setTip({ x, y: y - 4, text: label })} onMouseLeave={() => setTip(null)} />;
      })
    );
    const labels = (series[0]?.points || []).map((p, pi) => {
      const x = pad.l + (pi / Math.max(n - 1, 1)) * plotW;
      return <text key={pi} x={x} y={h - 2} textAnchor="middle" fontSize={10} fill="var(--color-text-muted, #999)">{p.label}</text>;
    });
    const legend = series.length > 1 ? series.map((s, si) => (
      <div key={si} style={{ display: "flex", alignItems: "center", gap: 6, fontSize: 12 }}>
        <span style={{ width: 16, height: 2, background: getColor(s.color, si), display: "inline-block" }} />
        <span>{s.label}</span>
      </div>
    )) : null;
    chart = (
      <>
        <svg width="100%" viewBox={`0 0 ${vw} ${h}`} preserveAspectRatio="xMidYMid meet" style={{ overflow: "visible" }}>
          {gridLines}{lines}{dots}{labels}{Tip}
        </svg>
        {legend && <div style={{ display: "flex", gap: 12, marginTop: 8 }}>{legend}</div>}
      </>
    );
  }

  return (
    <div id={id} className="c-chart" data-kind={kind}>
      {title && <h3 className="c-chart-title">{title}</h3>}
      {chart || <div className="c-chart-placeholder">Chart ({kind})</div>}
    </div>
  );
}

function AccordionView({
  id,
  items,
  renderMarkdown,
  renderChart,
  renderRoleMap,
}: {
  id: string;
  items: Array<{ title: string; components: ComponentData[] }>;
  renderMarkdown?: (md: string) => string;
  renderChart?: (comp: ComponentData) => React.ReactNode;
  renderRoleMap?: (comp: ComponentData) => React.ReactNode;
}) {
  const [openIndex, setOpenIndex] = React.useState<number | null>(null);
  return (
    <div id={id} className="c-accordion">
      {items.map((item, i) => (
        <div key={i} className={`c-accordion-item${openIndex === i ? " accordion-open" : ""}`}>
          <button className="accordion-head" onClick={() => setOpenIndex(openIndex === i ? null : i)}>
            {item.title}<span className="accordion-chevron">›</span>
          </button>
          {openIndex === i && (
            <div className="accordion-body">
              {(item.components || []).map((c, ci) => (
                <ComponentView key={ci} comp={c} index={ci} renderMarkdown={renderMarkdown} renderChart={renderChart} renderRoleMap={renderRoleMap} />
              ))}
            </div>
          )}
        </div>
      ))}
    </div>
  );
}

function ComponentView({
  comp,
  index,
  renderMarkdown,
  renderChart,
  renderRoleMap,
}: {
  comp: ComponentData;
  index: number;
  renderMarkdown?: (md: string) => string;
  renderChart?: (comp: ComponentData) => React.ReactNode;
  renderRoleMap?: (comp: ComponentData) => React.ReactNode;
}) {
  const id = (comp.id as string) || `c-${index}`;
  const md = (s: string) =>
    renderMarkdown ? (
      <div dangerouslySetInnerHTML={{ __html: renderMarkdown(s) }} />
    ) : (
      renderBlock(s)
    );

  switch (comp.type) {
    case "header": {
      const title = (comp.title as string) || "";
      const subtitle = comp.subtitle as string | undefined;
      const eyebrow = comp.eyebrow as string | undefined;
      return (
        <div id={id} className="c-header">
          {eyebrow && <div className="c-header-eyebrow">{eyebrow}</div>}
          <h1 className="c-header-title">{title}</h1>
          {subtitle && <p className="c-header-subtitle">{subtitle}</p>}
        </div>
      );
    }

    case "markdown": {
      const body = (comp.body as string) || "";
      return <div id={id} className="c-markdown">{md(body)}</div>;
    }

    case "callout": {
      const variant = (comp.variant as string) || "info";
      const title = comp.title as string | undefined;
      const body = (comp.body as string) || "";
      const links = (comp.links as Array<{ label: string; href: string; variant?: string }>) || [];
      return (
        <div id={id} className={`c-callout c-callout-${variant}`}>
          {title && <div className="c-callout-title">{renderInline(title)}</div>}
          <div className="c-callout-body c-markdown">{md(body)}</div>
          {links.length > 0 && (
            <div className="c-callout-links c-button-group">
              {links.map((l, i) => (
                <a key={i} href={l.href} className={`c-button c-button-${l.variant || "secondary"}`}>{l.label}</a>
              ))}
            </div>
          )}
        </div>
      );
    }

    case "card_grid": {
      const cards = (comp.cards as Array<{
        title: string;
        description?: string;
        badge?: { label: string; color?: string };
        href?: string;
      }>) || [];
      const connector = comp.connector as string | undefined;
      const gridClass = connector === "arrow" ? "c-card-grid c-card-grid-arrow" : "c-card-grid";
      return (
        <div id={id} className={gridClass}>
          {cards.map((card, i) => {
            const Tag = card.href ? "a" : "div";
            return (
              <React.Fragment key={i}>
                {connector === "arrow" && i > 0 && <div className="c-card-arrow">→</div>}
                <Tag className="c-card c-card-default" {...(card.href ? { href: card.href } : {})}>
                  <div className="c-card-top">
                    <h2 className="c-card-title">{card.title}</h2>
                    {card.badge && (
                      <span className={`c-badge c-badge-${card.badge.color || "default"}`}>
                        {card.badge.label}
                      </span>
                    )}
                  </div>
                  {card.description && <p className="c-card-desc">{renderInline(card.description)}</p>}
                </Tag>
              </React.Fragment>
            );
          })}
        </div>
      );
    }

    case "stat_grid": {
      const stats = (comp.stats as Array<{
        label: string;
        value: string;
        detail?: string;
        color?: string;
      }>) || [];
      const columns = (comp.columns as number) || stats.length;
      return (
        <div
          id={id}
          className="c-stat-grid"
          style={{ gridTemplateColumns: `repeat(${columns}, 1fr)` }}
        >
          {stats.map((s, i) => (
            <div key={i} className={`c-stat${s.color && s.color !== "default" ? ` c-stat-${s.color}` : ""}`}>
              <div className="c-stat-label">{s.label}</div>
              <div className="c-stat-value">{s.value}</div>
              {s.detail && <div className="c-stat-detail">{renderInline(s.detail)}</div>}
            </div>
          ))}
        </div>
      );
    }

    case "steps": {
      const items = (comp.items as Array<{ title: string; detail?: string }>) || [];
      const numbered = comp.numbered !== false;
      const Tag = numbered ? "ol" : "ul";
      return (
        <Tag id={id} className="c-steps">
          {items.map((item, i) => (
            <li key={i} className="c-step">
              {numbered ? (
                <div className="c-step-num">{i + 1}</div>
              ) : (
                <div className="c-step-bullet" />
              )}
              <div>
                <div className="c-step-title">{renderInline(item.title)}</div>
                {item.detail && <div className="c-step-detail">{renderInline(item.detail)}</div>}
              </div>
            </li>
          ))}
        </Tag>
      );
    }

    case "code": {
      const code = (comp.code as string) || "";
      const language = comp.language as string | undefined;
      return (
        <pre id={id} className="c-code" {...(language ? { "data-lang": language } : {})}>
          <code>{code}</code>
        </pre>
      );
    }

    case "image": {
      const src = (comp.src as string) || "";
      const alt = (comp.alt as string) || "";
      const caption = comp.caption as string | undefined;
      return (
        <figure id={id} className="c-image">
          <img src={assetSrc(src)} alt={alt} />
          {caption && <figcaption>{caption}</figcaption>}
        </figure>
      );
    }

    case "divider": {
      const label = comp.label as string | undefined;
      if (label) {
        return (
          <div id={id} className="c-divider c-divider-labeled">
            <span className="c-divider-line" />
            <span className="c-divider-label">{label}</span>
            <span className="c-divider-line" />
          </div>
        );
      }
      return <hr id={id} className="c-divider" />;
    }

    case "table": {
      const columns = (comp.columns as Array<{ key: string; label: string }>) || [];
      const rows = (comp.rows as Array<Record<string, unknown>>) || [];
      return (
        <div id={id} className="c-table-wrap">
          <table className="c-table">
            <thead>
              <tr>
                {columns.map((col, i) => (
                  <th key={i}>{col.label}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {rows.map((row, ri) => (
                <tr key={ri}>
                  {columns.map((col, ci) => (
                    <td key={ci}>{renderInline(String(row[col.key] ?? ""))}</td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      );
    }

    case "meta": {
      const fields = (comp.fields as Array<{ key: string; value: string }>) || [];
      return (
        <div id={id} className="c-meta">
          {fields.map((f, i) => (
            <div key={i} className="c-meta-item">
              <span className="c-meta-key">{f.key}</span>
              <span className="c-meta-value">{renderInline(f.value)}</span>
            </div>
          ))}
        </div>
      );
    }

    case "section": {
      const heading = comp.heading as string | undefined;
      const eyebrow = comp.eyebrow as string | undefined;
      const children = (comp.components as ComponentData[]) || [];
      return (
        <section id={id} className="c-section">
          {(eyebrow || heading) && (
            <div className="c-section-header">
              {eyebrow && <div className="c-section-eyebrow">{eyebrow}</div>}
              {heading && <h2 className="c-section-heading">{heading}</h2>}
            </div>
          )}
          {children.map((c, i) => (
            <ComponentView key={i} comp={c} index={i} renderMarkdown={renderMarkdown} renderChart={renderChart} renderRoleMap={renderRoleMap} />
          ))}
        </section>
      );
    }

    case "blockquote": {
      const body = (comp.body as string) || "";
      const attribution = comp.attribution as string | undefined;
      return (
        <figure id={id} className="c-blockquote">
          <blockquote><p>{renderInline(body)}</p></blockquote>
          {attribution && (
            <figcaption className="c-blockquote-attribution">— {attribution}</figcaption>
          )}
        </figure>
      );
    }

    case "badge": {
      const label = (comp.label as string) || "";
      const color = (comp.color as string) || "default";
      return <span id={id} className={`c-badge c-badge-${color}`}>{label}</span>;
    }

    case "status": {
      const label = (comp.label as string) || "";
      const color = (comp.color as string) || "default";
      return (
        <span id={id} className={`c-status c-status-${color}`}>
          <span className="c-status-dot" />
          <span>{label}</span>
        </span>
      );
    }

    case "progress_bar": {
      const value = Math.min(100, (comp.value as number) || 0);
      const label = comp.label as string | undefined;
      const color = (comp.color as string) || "default";
      const detail = comp.detail as string | undefined;
      return (
        <div id={id} className="c-progress">
          {(label || true) && (
            <div className="c-progress-labels">
              {label ? <span className="c-progress-label">{label}</span> : <span />}
              <span className="c-progress-value">{value}%</span>
            </div>
          )}
          <div className="c-progress-track" role="progressbar" aria-valuenow={value} aria-valuemin={0} aria-valuemax={100}>
            <div className={`c-progress-fill c-progress-fill-${color}`} style={{ width: `${value}%` }} />
          </div>
          {detail && <div className="c-progress-detail">{detail}</div>}
        </div>
      );
    }

    case "embed": {
      const src = (comp.src as string) || "";
      const title = (comp.title as string) || "Embedded video";
      const aspect = (comp.aspect as string) || "16/9";
      return (
        <div id={id} className="c-embed" style={{ aspectRatio: aspect }}>
          <iframe src={src} title={title} frameBorder="0" allowFullScreen />
        </div>
      );
    }

    case "timeline": {
      const items = (comp.items as Array<{ name: string; status: string }>) || [];
      return (
        <div id={id} className="c-timeline">
          {items.map((item, i) => (
            <div key={i} className={`c-timeline-phase ${item.status || "upcoming"}`}>
              <div className="c-timeline-dot" />
              <div className="c-timeline-label">{item.name}</div>
              <div className={`c-timeline-bar ${item.status || "upcoming"}`} />
            </div>
          ))}
        </div>
      );
    }

    case "split_compare": {
      const left = comp.left as { eyebrow?: string; title: string; stats: Array<{ label: string; value: string; color?: string }> };
      const right = comp.right as { eyebrow?: string; title: string; stats: Array<{ label: string; value: string; color?: string }> };
      return (
        <div id={id} className="c-split-compare">
          {[left, right].map((panel, pi) => (
            <div key={pi} className={`c-sc-panel c-sc-${pi === 0 ? "left" : "right"}`}>
              {panel.eyebrow && <div className="c-sc-eyebrow">{panel.eyebrow}</div>}
              <div className="c-sc-title">{panel.title}</div>
              <div className="c-sc-stats">
                {(panel.stats || []).map((s, si) => (
                  <div key={si} className="c-sc-stat">
                    <span className="c-sc-label">{s.label}</span>
                    <span className={`c-sc-value color-${s.color || "default"}`}>{s.value}</span>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      );
    }

    case "before_after": {
      const items = (comp.items as Array<{ title: string; before: string; after: string; after_context?: string }>) || [];
      const beforeLabel = (comp.before_label as string) || "Before";
      const afterLabel = (comp.after_label as string) || "After";
      return (
        <div id={id} className="c-before-after">
          {items.map((item, i) => (
            <div key={i} className="c-ba-card">
              <div className="c-ba-title">{item.title}</div>
              <div className="c-ba-before">{beforeLabel}: {item.before}</div>
              <div className="c-ba-after">{afterLabel}: <span className="c-ba-highlight">{item.after}</span>{item.after_context ? ` — ${item.after_context}` : ""}</div>
            </div>
          ))}
        </div>
      );
    }

    case "tabs": {
      const tabs = (comp.tabs as Array<{ label: string; components: ComponentData[] }>) || [];
      const [activeTab, setActiveTab] = React.useState(0);
      return (
        <div id={id} className="c-tabs">
          <div className="c-tab-buttons">
            {tabs.map((tab, ti) => (
              <button key={ti} className={`tab-btn${ti === activeTab ? " tab-btn-active" : ""}`} onClick={() => setActiveTab(ti)}>{tab.label}</button>
            ))}
          </div>
          {tabs.map((tab, ti) => (
            <div key={ti} className="tab-panel" style={{ display: ti === activeTab ? "block" : "none" }}>
              {(tab.components || []).map((c, ci) => (
                <ComponentView key={ci} comp={c} index={ci} renderMarkdown={renderMarkdown} renderChart={renderChart} renderRoleMap={renderRoleMap} />
              ))}
            </div>
          ))}
        </div>
      );
    }

    case "columns": {
      const cols = (comp.columns as ComponentData[][]) || [];
      const eqHeights = comp.equal_heights as boolean;
      return (
        <div id={id} className={`c-columns${eqHeights ? " c-columns-stretch" : ""}`} style={{ gridTemplateColumns: `repeat(${cols.length}, 1fr)` }}>
          {cols.map((col, ci) => (
            <div key={ci} className="c-column">
              {col.map((c, i) => (
                <ComponentView key={i} comp={c} index={i} renderMarkdown={renderMarkdown} renderChart={renderChart} renderRoleMap={renderRoleMap} />
              ))}
            </div>
          ))}
        </div>
      );
    }

    case "accordion": {
      const items = (comp.items as Array<{ title: string; components: ComponentData[] }>) || [];
      return <AccordionView id={id} items={items} renderMarkdown={renderMarkdown} renderChart={renderChart} renderRoleMap={renderRoleMap} />;
    }

    case "hero_banner": {
      const title = (comp.title as string) || "";
      const eyebrow = comp.eyebrow as string | undefined;
      const subtitle = comp.subtitle as string | undefined;
      const buttons = (comp.buttons as Array<{ label: string; href: string; variant?: string; external?: boolean }>) || [];
      return (
        <div id={id} className="c-hero">
          {eyebrow && <div className="c-hero-eyebrow">{eyebrow}</div>}
          <h1 className="c-hero-title">{title}</h1>
          {subtitle && <p className="c-hero-subtitle">{subtitle}</p>}
          {buttons.length > 0 && (
            <div className="c-hero-buttons">
              {buttons.map((b, i) => (
                <a key={i} className={`c-btn c-btn-${b.variant || "primary"}`} href={b.href}>{b.label}</a>
              ))}
            </div>
          )}
        </div>
      );
    }

    case "event_timeline": {
      const events = (comp.events as Array<{ date: string; title: string; summary?: string; severity?: string; source?: string; link?: string }>) || [];
      return (
        <div id={id} className="c-event-timeline">
          {events.map((ev, i) => (
            <div key={i} className={`c-event severity-${ev.severity || "minor"}`} data-severity={ev.severity || "minor"}>
              <div className="c-event-rail">
                <div className="c-event-dot" />
              </div>
              <div className="c-event-body">
                <div className="c-event-meta">
                  <span className="c-event-date">{ev.date}</span>
                  {ev.severity && <span className="c-event-severity">{ev.severity}</span>}
                  {ev.source && <span className="c-event-source">{ev.source}</span>}
                </div>
                <div className="c-event-title">{ev.link ? <a href={ev.link}>{ev.title}</a> : ev.title}</div>
                {ev.summary && <p className="c-event-summary">{renderInline(ev.summary)}</p>}
              </div>
            </div>
          ))}
        </div>
      );
    }

    case "tree": {
      const nodes = (comp.nodes as Array<Record<string, unknown>>) || [];
      const statusGlyphs: Record<string, string> = { completed: "✓", active: "●", blocked: "✕", priority: "!", upcoming: "○" };
      const renderNode = (node: Record<string, unknown>, depth: number): React.JSX.Element => {
        const children = (node.children as Array<Record<string, unknown>>) || [];
        const status = (node.status as string) || "default";
        const hasChildren = children.length > 0;
        return (
          <li className={`c-tree-node status-${status}`}>
            <div className="c-tree-row">
              {hasChildren && <span className="c-tree-chevron">▶</span>}
              <span className="c-tree-glyph">{statusGlyphs[status] || "·"}</span>
              <span className="c-tree-label">{node.label as string}</span>
              {node.note ? <span className="c-tree-note">{node.note as string}</span> : null}
            </div>
            {hasChildren && (
              <ul className="c-tree-children">
                {children.map((child, i) => <React.Fragment key={i}>{renderNode(child, depth + 1)}</React.Fragment>)}
              </ul>
            )}
          </li>
        );
      };
      return <div id={id} className="c-tree"><ul className="c-tree-root">{nodes.map((n, i) => <React.Fragment key={i}>{renderNode(n, 0)}</React.Fragment>)}</ul></div>;
    }

    case "selectable_grid": {
      const cards = (comp.cards as Array<{ title: string; eyebrow?: string; bullets?: string[]; body?: string }>) || [];
      const connector = comp.connector as string | undefined;
      const gridClass = connector === "arrow" ? "c-sel-cards c-sel-cards-arrow" : "c-sel-cards";
      return (
        <div id={id} className="c-selectable-grid">
          <div className={gridClass}>
            {cards.map((card, i) => (
              <div key={i} className="sel-card">
                {card.eyebrow && <div className="c-sel-eyebrow">{card.eyebrow}</div>}
                <div className="c-sel-title">{card.title}</div>
                {card.body && <div className="c-sel-body">{renderInline(card.body)}</div>}
                {card.bullets && (
                  <ul className="c-sel-bullets">
                    {card.bullets.map((b, bi) => <li key={bi}><span className="c-sel-bullet-dot" /><span>{renderInline(b)}</span></li>)}
                  </ul>
                )}
              </div>
            ))}
          </div>
        </div>
      );
    }

    case "resources": {
      const items = (comp.items as Array<{ title: string; href: string; description?: string; owner?: string }>) || [];
      return (
        <div id={id} className="c-resources">
          {items.map((item, i) => (
            <a key={i} className="c-resource" href={item.href}>
              <div className="c-resource-title">{item.title}</div>
              {item.description && <div className="c-resource-desc">{renderInline(item.description)}</div>}
              {item.owner && <div className="c-resource-owner">{item.owner}</div>}
            </a>
          ))}
        </div>
      );
    }

    case "button_group": {
      const buttons = (comp.buttons as Array<{ label: string; href: string; variant?: string; external?: boolean }>) || [];
      return (
        <div id={id} className="c-button-group">
          {buttons.map((b, i) => (
            <a key={i} className={`c-btn c-btn-${b.variant || "primary"}`} href={b.href} {...(b.external ? { target: "_blank", rel: "noopener noreferrer" } : {})}>{b.label}</a>
          ))}
        </div>
      );
    }

    case "definition_list": {
      const items = (comp.items as Array<{ term: string; definition: string }>) || [];
      return (
        <dl id={id} className="c-definition-list">
          {items.map((item, i) => (
            <div key={i} className="c-dl-row">
              <dt className="c-dl-term">{item.term}</dt>
              <dd className="c-dl-def">{renderInline(item.definition)}</dd>
            </div>
          ))}
        </dl>
      );
    }

    case "avatar": {
      const name = (comp.name as string) || "";
      const src = comp.src as string | undefined;
      const subtitle = comp.subtitle as string | undefined;
      const sizeClass = (comp.size as string) || "md";
      const initials = name.split(" ").map(w => w[0]).join("").slice(0, 2).toUpperCase();
      if (subtitle) {
        return (
          <div id={id} className="c-avatar-row">
            <div className={`c-avatar c-avatar-${sizeClass}`}>
              {src ? <img src={assetSrc(src)} alt={name} /> : <span className="c-avatar-initials">{initials}</span>}
            </div>
            <div className="c-avatar-meta">
              <div className="c-avatar-name">{name}</div>
              <div className="c-avatar-sub">{subtitle}</div>
            </div>
          </div>
        );
      }
      return (
        <div id={id} className={`c-avatar c-avatar-${sizeClass}`}>
          {src ? <img src={assetSrc(src)} alt={name} /> : <span className="c-avatar-initials">{initials}</span>}
        </div>
      );
    }

    case "avatar_group": {
      const avatars = (comp.avatars as Array<{ name: string; src?: string }>) || [];
      const max = (comp.max as number) || 5;
      const sizeClass = (comp.size as string) || "md";
      const visible = avatars.slice(0, max);
      const overflow = avatars.length - max;
      return (
        <div id={id} className={`c-avatar-group c-avatar-group-${sizeClass}`}>
          {visible.map((a, i) => {
            const initials = a.name.split(" ").map(w => w[0]).join("").slice(0, 2).toUpperCase();
            return (
              <div key={i} className={`c-avatar c-avatar-${sizeClass}`} title={a.name}>
                {a.src ? <img src={assetSrc(a.src)} alt={a.name} /> : <span className="c-avatar-initials">{initials}</span>}
              </div>
            );
          })}
          {overflow > 0 && <div className={`c-avatar c-avatar-${sizeClass} c-avatar-more`}>+{overflow}</div>}
        </div>
      );
    }

    case "breadcrumb": {
      const items = (comp.items as Array<{ label: string; href?: string }>) || [];
      return (
        <nav id={id} className="c-breadcrumb">
          {items.map((item, i) => (
            <span key={i}>
              {i > 0 && <span className="c-breadcrumb-sep">/</span>}
              {item.href ? <a href={item.href}>{item.label}</a> : <span>{item.label}</span>}
            </span>
          ))}
        </nav>
      );
    }

    case "tag": {
      const label = (comp.label as string) || "";
      const color = (comp.color as string) || "default";
      return <span id={id} className={`c-tag c-tag-${color}`}>{label}</span>;
    }

    case "kbd": {
      const keys = (comp.keys as string[]) || [];
      return (
        <span id={id} className="c-kbd">
          {keys.map((k, i) => (
            <span key={i}>
              {i > 0 && <span className="c-kbd-sep">+</span>}
              <kbd>{k}</kbd>
            </span>
          ))}
        </span>
      );
    }

    case "empty_state": {
      const title = (comp.title as string) || "";
      const body = comp.body as string | undefined;
      const action = comp.action as { label: string; href: string } | undefined;
      return (
        <div id={id} className="c-empty-state">
          <h3 className="c-empty-title">{title}</h3>
          {body && <p className="c-empty-body">{renderInline(body)}</p>}
          {action && <a className="c-btn c-btn-primary" href={action.href}>{action.label}</a>}
        </div>
      );
    }

    case "venn": {
      const sets = (comp.sets as Array<{ label: string; color?: string }>) || [];
      const overlaps = (comp.overlaps as Array<{ sets: number[]; label?: string }>) || [];
      const title = comp.title as string | undefined;
      return (
        <div id={id} className="c-venn">
          {title && <h3 className="c-venn-title">{title}</h3>}
          <div className="c-venn-diagram">
            {sets.map((s, i) => (
              <div key={i} className={`c-venn-set c-venn-set-${i} c-venn-color-${s.color || "default"}`}>
                <span>{s.label}</span>
              </div>
            ))}
          </div>
          {overlaps.length > 0 && (
            <div className="c-venn-overlaps">
              {overlaps.map((o, i) => o.label && (
                <div key={i} className="c-venn-overlap">
                  {sets.filter((_, si) => o.sets.includes(si)).map(s => s.label).join(" ∩ ")}: {o.label}
                </div>
              ))}
            </div>
          )}
        </div>
      );
    }

    case "chart": {
      if (renderChart) {
        return <div id={id} className="c-chart">{renderChart(comp)}</div>;
      }
      return <ChartSVG id={id} comp={comp} />;
    }

    case "chart_group": {
      const title = comp.title as string | undefined;
      const cols = (comp.columns as number) || 2;
      const children = (comp.components as ComponentData[]) || [];
      return (
        <div id={id} className="c-chart-group" style={{ display: "grid", gridTemplateColumns: `repeat(${cols}, 1fr)`, gap: 16 }}>
          {title && <h3 className="c-chart-group-title" style={{ gridColumn: "1 / -1" }}>{title}</h3>}
          {children.map((child, ci) => (
            <ComponentView key={ci} comp={child} index={ci} renderMarkdown={renderMarkdown} renderChart={renderChart} renderRoleMap={renderRoleMap} />
          ))}
        </div>
      );
    }

    case "role_map": {
      const title = comp.title as string | undefined;
      if (renderRoleMap) return <div id={id} className="c-role-map">{renderRoleMap(comp)}</div>;
      return (
        <div id={id} className="c-role-map">
          {title && <h3 className="c-role-map-title">{title}</h3>}
          <div className="c-role-map-placeholder">Roles configured in site settings</div>
        </div>
      );
    }

    default:
      return (
        <div id={id} className="c-unsupported" data-type={comp.type}>
          <em>Unsupported component: {comp.type}</em>
        </div>
      );
  }
}

function DeckRenderer({ slides, renderMarkdown, renderChart, renderRoleMap }: { slides: SlideData[]; renderMarkdown?: (md: string) => string; renderChart?: (comp: ComponentData) => React.ReactNode; renderRoleMap?: (comp: ComponentData) => React.ReactNode }) {
  const [current, setCurrent] = React.useState(0);
  const trackRef = React.useRef<HTMLDivElement>(null);

  const go = React.useCallback((n: number) => {
    setCurrent(Math.max(0, Math.min(slides.length - 1, n)));
  }, [slides.length]);

  React.useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (e.key === "ArrowRight" || e.key === "ArrowDown") setCurrent(c => Math.min(slides.length - 1, c + 1));
      if (e.key === "ArrowLeft" || e.key === "ArrowUp") setCurrent(c => Math.max(0, c - 1));
    };
    document.addEventListener("keydown", handler);
    return () => document.removeEventListener("keydown", handler);
  }, [slides.length]);

  React.useEffect(() => {
    document.body.classList.add("shell-deck");
    return () => { document.body.classList.remove("shell-deck"); };
  }, []);

  return (
    <div className="deck-root">
      <div className="deck-viewport">
        <div className="deck-track" ref={trackRef} style={{ transform: `translateX(-${current * 100}%)` }}>
          {slides.map((slide, si) => (
            <div key={si} className={`deck-slide${slide.hide_label || slide.cover ? " deck-slide-cover" : ""}`} data-label={slide.label}>
              <div className="deck-inner">
                {!slide.hide_label && <div className="deck-label">{slide.label}</div>}
                {(slide.components ?? []).map((comp, ci) => (
                  <ComponentView key={ci} comp={comp} index={ci} renderMarkdown={renderMarkdown} renderChart={renderChart} renderRoleMap={renderRoleMap} />
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>
      <div className="deck-nav">
        <button className="deck-arrow deck-prev" onClick={() => go(current - 1)} style={current === 0 ? { visibility: "hidden" } : undefined}>← {slides[current - 1]?.label}</button>
        <span className="deck-nav-label">{slides[current]?.label}</span>
        <button className="deck-arrow deck-next" onClick={() => go(current + 1)} style={current >= slides.length - 1 ? { visibility: "hidden" } : undefined}>{slides[current + 1]?.label} →</button>
      </div>
    </div>
  );
}

function FreshnessBanner({ freshness }: { freshness?: FreshnessData | "never" }) {
  if (!freshness || freshness === "never") return null;
  const f = freshness as FreshnessData;
  if (!f.updated || !f.review_every) return null;

  const cadenceMap: Record<string, number> = {
    weekly: 7, monthly: 30, quarterly: 90, yearly: 365, annually: 365,
  };
  let cadenceDays = cadenceMap[f.review_every];
  if (!cadenceDays) {
    const m = f.review_every.match(/^(\d+)(d|w|m|y)$/);
    if (m) {
      const n = parseInt(m[1], 10);
      cadenceDays = m[2] === "d" ? n : m[2] === "w" ? n * 7 : m[2] === "m" ? n * 30 : n * 365;
    }
  }
  if (!cadenceDays) return null;

  const updated = new Date(f.updated);
  const now = new Date();
  const elapsed = Math.floor((now.getTime() - updated.getTime()) / 86400000);
  const dueIn = cadenceDays - elapsed;

  let variant: string;
  let title: string;
  let headline: string;
  if (dueIn > 7) return null;
  if (dueIn > 0) {
    variant = "warn";
    title = "Review due soon";
    headline = dueIn === 1 ? "Review is due in 1 day." : `Review is due in ${dueIn} days.`;
  } else if (dueIn === 0) {
    variant = "warn";
    title = "Review due soon";
    headline = "Review is due today.";
  } else {
    variant = "danger";
    title = "Review overdue";
    headline = `Review is ${-dueIn} ${-dueIn === 1 ? "day" : "days"} overdue.`;
  }

  const meta = [
    `Last updated: ${f.updated} (${elapsed} days ago)`,
    `Review cadence: every ${f.review_every}`,
    f.owner ? `Owner: ${f.owner}` : null,
  ].filter(Boolean).join(". ");

  return (
    <div className={`c-callout c-callout-${variant} c-freshness-banner`}>
      <div className="c-callout-title">{title}</div>
      <div className="c-callout-body">{headline} {meta}.</div>
    </div>
  );
}

export function PageRenderer({ page, renderMarkdown, renderChart, renderRoleMap }: PageRendererProps) {
  if (page.shell === "deck" && page.slides && page.slides.length > 0) {
    return <DeckRenderer slides={page.slides} renderMarkdown={renderMarkdown} renderChart={renderChart} renderRoleMap={renderRoleMap} />;
  }
  const components = page.components ?? [];
  return (
    <div>
      <FreshnessBanner freshness={page.freshness} />
      {components.map((comp, i) => (
        <ComponentView key={i} comp={comp} index={i} renderMarkdown={renderMarkdown} renderChart={renderChart} renderRoleMap={renderRoleMap} />
      ))}
    </div>
  );
}

export { ComponentView, DeckRenderer, type SlideData, type PageData, type ComponentData, type PageRendererProps };
"####;

fn generate_editor(out: &mut String) {
    let components = component_defs();

    let enums: Vec<(&str, Vec<&str>)> = vec![
        ("CalloutVariant", vec!["info", "warn", "success", "danger"]),
        (
            "SemColor",
            vec!["default", "green", "yellow", "red", "teal"],
        ),
        ("Align", vec!["left", "right", "center"]),
        ("Connector", vec!["none", "dots_line", "arrow"]),
        ("TimelineStatus", vec!["completed", "active", "upcoming"]),
        ("EventSeverity", vec!["major", "minor", "info"]),
        ("EventFilter", vec!["all", "major"]),
        (
            "TreeStatus",
            vec![
                "default",
                "completed",
                "active",
                "blocked",
                "priority",
                "upcoming",
            ],
        ),
        (
            "TreeFilter",
            vec!["all", "incomplete", "blocked", "priority"],
        ),
        ("ButtonVariant", vec!["primary", "secondary", "ghost"]),
        ("IconSize", vec!["xs", "sm", "md", "lg", "xl"]),
        ("AvatarSize", vec!["sm", "md", "lg", "xl"]),
        ("ChartKind", vec!["pie", "bar", "timeseries"]),
        ("ChartOrientation", vec!["vertical", "horizontal"]),
        ("Interaction", vec!["single_select", "multi_select", "none"]),
    ];

    type InterfaceDef<'a> = (&'a str, Vec<(&'a str, &'a str, bool)>);
    let interfaces: Vec<InterfaceDef> = vec![
        (
            "MetaField",
            vec![("key", "string", true), ("value", "string", true)],
        ),
        (
            "Stat",
            vec![
                ("label", "string", true),
                ("value", "string", true),
                ("detail", "string", false),
                ("color", "SemColor", false),
            ],
        ),
        (
            "Card",
            vec![
                ("title", "string", true),
                ("description", "string", false),
                ("href", "string", false),
                ("color", "SemColor", false),
            ],
        ),
        (
            "BeforeAfterItem",
            vec![
                ("title", "string", true),
                ("before", "string", true),
                ("after", "string", true),
                ("after_context", "string", false),
            ],
        ),
        (
            "Step",
            vec![("title", "string", true), ("detail", "string", false)],
        ),
        (
            "TableColumn",
            vec![("key", "string", true), ("label", "string", true)],
        ),
        (
            "EventItem",
            vec![
                ("date", "string", true),
                ("title", "string", true),
                ("summary", "string", false),
                ("severity", "EventSeverity", false),
                ("source", "string", false),
            ],
        ),
        (
            "BreadcrumbItem",
            vec![("label", "string", true), ("href", "string", false)],
        ),
        (
            "ButtonConfig",
            vec![
                ("label", "string", true),
                ("href", "string", true),
                ("variant", "ButtonVariant", false),
            ],
        ),
        (
            "DefinitionItem",
            vec![("term", "string", true), ("definition", "string", true)],
        ),
        (
            "AvatarConfig",
            vec![("name", "string", true), ("src", "string", false)],
        ),
        (
            "ResourceItem",
            vec![
                ("title", "string", true),
                ("href", "string", true),
                ("description", "string", false),
                ("owner", "string", false),
            ],
        ),
        (
            "ChartPoint",
            vec![
                ("label", "string", true),
                ("value", "number", true),
                ("color", "SemColor", false),
            ],
        ),
        (
            "ChartSeries",
            vec![("label", "string", true), ("color", "SemColor", false)],
        ),
        (
            "VennSet",
            vec![("label", "string", true), ("color", "SemColor", false)],
        ),
        (
            "TimelineItem",
            vec![("name", "string", true), ("status", "TimelineStatus", true)],
        ),
        (
            "SelectableCard",
            vec![
                ("title", "string", true),
                ("eyebrow", "string", false),
                ("body", "string", false),
                ("color", "SemColor", false),
            ],
        ),
        ("Tab", vec![("label", "string", true)]),
        ("AccordionItem", vec![("title", "string", true)]),
    ];

    let long_fields = ["body", "code", "summary", "definition", "description"];

    let icons: Vec<(&str, &str)> = vec![
        ("header", "H"),
        ("markdown", "Aa"),
        ("callout", "!"),
        ("card_grid", ":::"),
        ("stat_grid", "#"),
        ("steps", "1."),
        ("code", "</>"),
        ("image", "img"),
        ("divider", "---"),
        ("table", "|||"),
        ("section", "\u{00a7}"),
        ("columns", "||"),
        ("tabs", "\u{2291}"),
        ("accordion", "\u{2261}"),
        ("chart", "\u{25d4}"),
        ("chart_group", "\u{25d4}\u{25d4}"),
    ];

    let get_icon = |comp_type: &str| -> String {
        for (t, icon) in &icons {
            if *t == comp_type {
                return (*icon).to_string();
            }
        }
        // first letter uppercased
        let first = comp_type.chars().next().unwrap_or('?');
        first.to_uppercase().to_string()
    };

    let make_label = |comp_type: &str| -> String {
        comp_type
            .replace('_', " ")
            .split_whitespace()
            .map(|w| {
                let mut c = w.chars();
                match c.next() {
                    None => String::new(),
                    Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                }
            })
            .collect::<Vec<_>>()
            .join(" ")
    };

    // Helper closures
    let find_enum = |type_name: &str| -> Option<&Vec<&str>> {
        enums.iter().find(|(n, _)| *n == type_name).map(|(_, v)| v)
    };

    let find_interface = |type_name: &str| -> Option<&Vec<(&str, &str, bool)>> {
        interfaces
            .iter()
            .find(|(n, _)| *n == type_name)
            .map(|(_, v)| v)
    };

    // ── 1. EDITOR_TYPES constant ───────────────────────────────────────────
    out.push_str("\nconst EDITOR_TYPES: Array<{type: string; label: string; icon: string}> = [\n");
    for (comp_type, _) in &components {
        let label = make_label(comp_type);
        let icon = get_icon(comp_type);
        out.push_str(&format!(
            "  {{ type: \"{}\", label: \"{}\", icon: \"{}\" }},\n",
            comp_type, label, icon
        ));
    }
    out.push_str("];\n\n");

    // ── 2. newEditorComponent function ────────────────────────────────────
    out.push_str("function newEditorComponent(type: string): ComponentData {\n");
    out.push_str("  switch (type) {\n");
    for (comp_type, fields) in &components {
        out.push_str(&format!(
            "    case \"{}\": return {{ type: \"{}\"",
            comp_type, comp_type
        ));
        for (fname, ftype) in fields {
            let is_optional = fname.ends_with('?');
            if is_optional {
                continue;
            } // skip optional fields in defaults
            let clean = fname.trim_end_matches('?');
            let default_val = if *ftype == "string" {
                "\"\"".to_string()
            } else if *ftype == "number" {
                "0".to_string()
            } else if *ftype == "boolean" {
                "false".to_string()
            } else if ftype.ends_with("[]") || *ftype == "Component[]" || *ftype == "Component[][]"
            {
                "[]".to_string()
            } else if find_enum(ftype).is_some() {
                let variants = find_enum(ftype).unwrap();
                format!("\"{}\"", variants[0])
            } else {
                // complex type, skip
                continue;
            };
            out.push_str(&format!(", {}: {}", clean, default_val));
        }
        out.push_str(" };\n");
    }
    out.push_str("    default: return { type } as ComponentData;\n");
    out.push_str("  }\n");
    out.push_str("}\n\n");

    // ── 3. ComponentFieldEditor ────────────────────────────────────────────
    out.push_str("function ComponentFieldEditor({ comp, onChange }: { comp: ComponentData; onChange: (c: ComponentData) => void }) {\n");
    out.push_str("  switch (comp.type) {\n");

    for (comp_type, fields) in &components {
        out.push_str(&format!("    case \"{}\": return (<>\n", comp_type));
        for (fname, ftype) in fields {
            let is_optional = fname.ends_with('?');
            let clean = fname.trim_end_matches('?');
            let display_name = make_label(clean);

            if *ftype == "string" {
                if long_fields.contains(&clean) {
                    // textarea
                    out.push_str(&format!(
                        "      <textarea className=\"pe-textarea\" placeholder=\"{}\" value={{(comp.{} as string) || \"\"}} onChange={{(e) => onChange({{...comp, {}: e.target.value}})}} />\n",
                        display_name, clean, clean
                    ));
                } else {
                    // input
                    if is_optional {
                        out.push_str(&format!(
                            "      <input className=\"pe-input\" placeholder=\"{}\" value={{(comp.{} as string) || \"\"}} onChange={{(e) => onChange({{...comp, {}: e.target.value || undefined}})}} />\n",
                            display_name, clean, clean
                        ));
                    } else {
                        out.push_str(&format!(
                            "      <input className=\"pe-input\" placeholder=\"{}\" value={{(comp.{} as string) || \"\"}} onChange={{(e) => onChange({{...comp, {}: e.target.value}})}} />\n",
                            display_name, clean, clean
                        ));
                    }
                }
            } else if *ftype == "number" {
                out.push_str(&format!(
                    "      <input className=\"pe-input\" type=\"number\" placeholder=\"{}\" value={{(comp.{} as number) ?? \"\"}} onChange={{(e) => onChange({{...comp, {}: e.target.value ? Number(e.target.value) : undefined}})}} />\n",
                    display_name, clean, clean
                ));
            } else if *ftype == "boolean" {
                out.push_str(&format!(
                    "      <label className=\"pe-checkbox-label\"><input type=\"checkbox\" checked={{(comp.{} as boolean) || false}} onChange={{(e) => onChange({{...comp, {}: e.target.checked || undefined}})}}/> {}</label>\n",
                    clean, clean, display_name
                ));
            } else if let Some(variants) = find_enum(ftype) {
                // select
                out.push_str(&format!(
                    "      <select className=\"pe-select\" value={{(comp.{} as string) || \"\"}} onChange={{(e) => onChange({{...comp, {}: e.target.value || undefined}})}}>\\n        <option value=\"\">-- {} --</option>\n",
                    clean, clean, display_name
                ));
                for v in variants.iter() {
                    out.push_str(&format!("        <option value=\"{}\">{}</option>\n", v, v));
                }
                out.push_str("      </select>\n");
            } else if *ftype == "Component[]" {
                out.push_str(&format!(
                    "      <NestedComponentList components={{(comp.{} as ComponentData[]) || []}} onChange={{(comps) => onChange({{...comp, {}: comps}})}} />\n",
                    clean, clean
                ));
            } else if *ftype == "Component[][]" {
                // columns: Component[][]
                out.push_str(&format!(
                    "      <div className=\"pe-columns-editor\">{{((comp.{} as ComponentData[][]) || []).map((col, ci) => (<div key={{ci}} className=\"pe-column-wrap\"><div className=\"pe-column-label\">Column {{ci+1}}</div><NestedComponentList components={{col}} onChange={{(comps) => {{ const next = [...((comp.{} as ComponentData[][]) || [])]; next[ci] = comps; onChange({{...comp, {}: next}}); }}}} /></div>))}}</div>\n",
                    clean, clean, clean
                ));
            } else if let Some(elem_type) = ftype.strip_suffix("[]") {
                if elem_type == "string" {
                    // string[] — simple tag list (e.g. keys for kbd)
                    out.push_str(&format!(
                        "      <textarea className=\"pe-textarea\" placeholder=\"{}\" value={{((comp.{} as string[]) || []).join(\", \")}} onChange={{(e) => onChange({{...comp, {}: e.target.value.split(\",\").map((s: string) => s.trim()).filter(Boolean)}})}} />\n",
                        display_name, clean, clean
                    ));
                } else if let Some(iface_fields) = find_interface(elem_type) {
                    // known interface — inline list editor
                    let field_name = clean;
                    let iface_fields_clone: Vec<(&str, &str, bool)> = iface_fields.to_vec();
                    out.push_str(&format!(
                        "      <div className=\"pe-list-editor\">\n        {{((comp.{} as Array<Record<string, unknown>>) || []).map((item, i) => (\n          <div key={{i}} className=\"pe-list-item pe-list-item-row\">\n",
                        field_name
                    ));
                    for (ifield, itype, _ireq) in &iface_fields_clone {
                        let ifield_display = make_label(ifield);
                        if let Some(ivariants) = find_enum(itype) {
                            out.push_str(&format!(
                                "            <select className=\"pe-select\" value={{(item.{} as string) || \"\"}} onChange={{(e) => {{ const next = [...((comp.{} as Array<Record<string, unknown>>) || [])]; next[i] = {{...item, {}: e.target.value || undefined}}; onChange({{...comp, {}: next}}); }}}}>\\n              <option value=\"\">-- {} --</option>\n",
                                ifield, field_name, ifield, field_name, ifield_display
                            ));
                            for iv in ivariants.iter() {
                                out.push_str(&format!(
                                    "              <option value=\"{}\">{}</option>\n",
                                    iv, iv
                                ));
                            }
                            out.push_str("            </select>\n");
                        } else if *itype == "number" {
                            out.push_str(&format!(
                                "            <input className=\"pe-input pe-input-short\" type=\"number\" placeholder=\"{}\" value={{(item.{} as number) ?? \"\"}} onChange={{(e) => {{ const next = [...((comp.{} as Array<Record<string, unknown>>) || [])]; next[i] = {{...item, {}: e.target.value ? Number(e.target.value) : undefined}}; onChange({{...comp, {}: next}}); }}}} />\n",
                                ifield_display, ifield, field_name, ifield, field_name
                            ));
                        } else {
                            let placeholder = ifield_display.clone();
                            out.push_str(&format!(
                                "            <input className=\"pe-input pe-input-short\" placeholder=\"{}\" value={{(item.{} as string) || \"\"}} onChange={{(e) => {{ const next = [...((comp.{} as Array<Record<string, unknown>>) || [])]; next[i] = {{...item, {}: e.target.value}}; onChange({{...comp, {}: next}}); }}}} />\n",
                                placeholder, ifield, field_name, ifield, field_name
                            ));
                        }
                    }
                    // required fields for default new item
                    let required_defaults: Vec<String> = iface_fields_clone
                        .iter()
                        .filter(|(_, _, req)| *req)
                        .map(|(f, t, _)| {
                            if *t == "number" {
                                format!("{}: 0", f)
                            } else {
                                format!("{}: \"\"", f)
                            }
                        })
                        .collect();
                    let default_item = format!("{{{}}}", required_defaults.join(", "));
                    out.push_str(&format!(
                        "            {{((comp.{} as unknown[]) || []).length > 1 && <button className=\"pe-list-remove\" onClick={{() => onChange({{...comp, {}: ((comp.{} as unknown[]) || []).filter((_: unknown, j: number) => j !== i)}})}}>×</button>}}\n",
                        field_name, field_name, field_name
                    ));
                    out.push_str("          </div>\n        ))}\n");
                    out.push_str(&format!(
                        "        <button className=\"pe-list-add\" onClick={{() => onChange({{...comp, {}: [...((comp.{} as unknown[]) || []), {}]}})}}> + Add {}</button>\n",
                        field_name, field_name, default_item, elem_type
                    ));
                    out.push_str("      </div>\n");
                } else {
                    // unknown array element type — YAML fallback
                    out.push_str(&format!(
                        "      <textarea className=\"pe-textarea\" placeholder=\"{}\" value={{yamlStringify(comp.{} ?? [])}} onChange={{(e) => {{ try {{ onChange({{...comp, {}: yamlParse(e.target.value)}}); }} catch(_) {{}} }}}} />\n",
                        display_name, clean, clean
                    ));
                }
            } else {
                // complex / unknown — YAML fallback
                if !is_optional {
                    out.push_str(&format!(
                        "      <textarea className=\"pe-textarea\" placeholder=\"{}\" value={{yamlStringify(comp.{} ?? null)}} onChange={{(e) => {{ try {{ onChange({{...comp, {}: yamlParse(e.target.value)}}); }} catch(_) {{}} }}}} />\n",
                        display_name, clean, clean
                    ));
                } else {
                    out.push_str(&format!(
                        "      <textarea className=\"pe-textarea\" placeholder=\"{}\" value={{yamlStringify(comp.{} ?? null)}} onChange={{(e) => {{ try {{ onChange({{...comp, {}: yamlParse(e.target.value) || undefined}}); }} catch(_) {{}} }}}} />\n",
                        display_name, clean, clean
                    ));
                }
            }
        }
        out.push_str("    </>);\n");
    }

    out.push_str(
        "    default: return <div className=\"pe-unknown\">Unknown component: {comp.type}</div>;\n",
    );
    out.push_str("  }\n");
    out.push_str("}\n\n");

    // ── 4. NestedComponentList ─────────────────────────────────────────────
    out.push_str(r#"function NestedComponentList({ components, onChange }: { components: ComponentData[]; onChange: (comps: ComponentData[]) => void }) {
  const [addOpen, setAddOpen] = React.useState(false);
  return (
    <div className="pe-nested">
      {components.map((c, i) => (
        <div key={i} className="pe-component pe-component-nested">
          <div className="pe-component-header">
            <span className="pe-component-type">{c.type}</span>
            <div className="pe-component-actions">
              {i > 0 && <button className="pe-move-btn" onClick={() => { const n = [...components]; [n[i-1], n[i]] = [n[i], n[i-1]]; onChange(n); }}>&uarr;</button>}
              {i < components.length - 1 && <button className="pe-move-btn" onClick={() => { const n = [...components]; [n[i], n[i+1]] = [n[i+1], n[i]]; onChange(n); }}>&darr;</button>}
              <button className="pe-remove-btn" onClick={() => onChange(components.filter((_, j) => j !== i))}>&times;</button>
            </div>
          </div>
          <div className="pe-component-body">
            <ComponentFieldEditor comp={c} onChange={(updated) => { const n = [...components]; n[i] = updated; onChange(n); }} />
          </div>
        </div>
      ))}
      <div className="pe-add-wrap">
        <button className="pe-list-add" onClick={() => setAddOpen(!addOpen)}>+ Add block</button>
        {addOpen && <div className="pe-add-menu">{EDITOR_TYPES.map(t => <button key={t.type} className="pe-add-option" onClick={() => { onChange([...components, newEditorComponent(t.type)]); setAddOpen(false); }}><span className="pe-add-option-icon">{t.icon}</span><span className="pe-add-option-label">{t.label}</span></button>)}</div>}
      </div>
    </div>
  );
}

"#);

    // ── 5. KazamComponentEditor ────────────────────────────────────────────
    out.push_str(r#"function KazamComponentEditor({ comp, index, onChange, onRemove, onMove, isFirst, isLast }: {
  comp: ComponentData; index: number;
  onChange: (index: number, data: ComponentData) => void;
  onRemove: (index: number) => void;
  onMove: (index: number, direction: -1 | 1) => void;
  isFirst: boolean; isLast: boolean;
}) {
  const label = EDITOR_TYPES.find(t => t.type === comp.type)?.label || comp.type;
  return (
    <div className="pe-component">
      <div className="pe-component-header">
        <span className="pe-component-type">{label}</span>
        <div className="pe-component-actions">
          {!isFirst && <button className="pe-move-btn" onClick={() => onMove(index, -1)} title="Move up">&uarr;</button>}
          {!isLast && <button className="pe-move-btn" onClick={() => onMove(index, 1)} title="Move down">&darr;</button>}
          <button className="pe-remove-btn" onClick={() => onRemove(index)}>&times;</button>
        </div>
      </div>
      <div className="pe-component-body">
        <ComponentFieldEditor comp={comp} onChange={(c) => onChange(index, c)} />
      </div>
    </div>
  );
}

"#);

    // ── 6. PageEditor ──────────────────────────────────────────────────────
    out.push_str(r#"export function PageEditor({ page, onChange }: { page: PageData; onChange: (page: PageData) => void }) {
  const [addMenuOpen, setAddMenuOpen] = React.useState(false);
  const comps = page.components || [];

  const updateComponent = React.useCallback((index: number, data: ComponentData) => {
    const next = [...comps]; next[index] = data;
    onChange({ ...page, components: next });
  }, [page, comps, onChange]);

  const removeComponent = React.useCallback((index: number) => {
    onChange({ ...page, components: comps.filter((_, i) => i !== index) });
  }, [page, comps, onChange]);

  const moveComponent = React.useCallback((index: number, direction: -1 | 1) => {
    const next = [...comps];
    const target = index + direction;
    if (target < 0 || target >= next.length) return;
    [next[index], next[target]] = [next[target], next[index]];
    onChange({ ...page, components: next });
  }, [page, comps, onChange]);

  const addComponent = React.useCallback((type: string) => {
    onChange({ ...page, components: [...comps, newEditorComponent(type)] });
    setAddMenuOpen(false);
  }, [page, comps, onChange]);

  return (
    <div className="pe-root">
      <div className="pe-meta">
        <input className="pe-input pe-input-title" placeholder="Untitled" value={page.title || ""} onChange={(e) => onChange({ ...page, title: e.target.value })} />
        <input className="pe-input pe-input-subtitle" placeholder="Add a subtitle..." value={page.subtitle || ""} onChange={(e) => onChange({ ...page, subtitle: e.target.value || undefined })} />
      </div>
      <div className="pe-components">
        {comps.map((comp, i) => (
          <KazamComponentEditor key={i} comp={comp} index={i} onChange={updateComponent} onRemove={removeComponent} onMove={moveComponent} isFirst={i === 0} isLast={i === comps.length - 1} />
        ))}
      </div>
      <div className="pe-add-wrap">
        <button className="pe-add-btn" onClick={() => setAddMenuOpen(!addMenuOpen)}>
          {comps.length === 0 ? "Click to add your first block..." : "+ Add block"}
        </button>
        {addMenuOpen && (
          <div className="pe-add-menu">
            {EDITOR_TYPES.map(t => (
              <button key={t.type} className="pe-add-option" onClick={() => addComponent(t.type)}>
                <span className="pe-add-option-icon">{t.icon}</span>
                <span><span className="pe-add-option-label">{t.label}</span></span>
              </button>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

export { KazamComponentEditor, ComponentFieldEditor, NestedComponentList, EDITOR_TYPES, newEditorComponent };
"#);
}

fn emit_enum(out: &mut String, name: &str, variants: &[&str]) {
    out.push_str("export type ");
    out.push_str(name);
    out.push_str(" = ");
    for (i, v) in variants.iter().enumerate() {
        if i > 0 {
            out.push_str(" | ");
        }
        out.push('"');
        out.push_str(v);
        out.push('"');
    }
    out.push_str(";\n\n");
}

fn emit_interface(out: &mut String, name: &str, fields: &[(&str, &str)]) {
    out.push_str("export interface ");
    out.push_str(name);
    out.push_str(" {\n");
    for (name, ts_type) in fields {
        if let Some(stripped) = name.strip_suffix('?') {
            out.push_str("  ");
            out.push_str(stripped);
            out.push_str("?: ");
        } else {
            out.push_str("  ");
            out.push_str(name);
            out.push_str(": ");
        }
        out.push_str(ts_type);
        out.push_str(";\n");
    }
    out.push_str("}\n\n");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn typescript_output_contains_key_types() {
        let ts = generate_typescript();
        assert!(ts.contains("export type Shell ="));
        assert!(ts.contains("export interface Page {"));
        assert!(ts.contains("export interface SiteConfig {"));
        assert!(ts.contains("export type Component ="));
        assert!(ts.contains("export interface ValidationError {"));
        assert!(ts.contains("{ type: \"header\""));
        assert!(ts.contains("{ type: \"chart\""));
        assert!(ts.contains("{ type: \"role_map\""));
    }
}
