use anyhow::Result;

pub fn emit_typescript() -> Result<()> {
    print!("{}", generate_typescript());
    Ok(())
}

fn generate_typescript() -> String {
    let mut out = String::with_capacity(8192);
    out.push_str("// Auto-generated by `kazam sdk emit` — do not edit\n\n");

    // Enums
    emit_enum(&mut out, "Shell", &["standard", "document", "deck"]);
    emit_enum(&mut out, "Align", &["left", "right", "center"]);
    emit_enum(
        &mut out,
        "SemColor",
        &["default", "green", "yellow", "red", "teal"],
    );
    emit_enum(
        &mut out,
        "CalloutVariant",
        &["info", "warn", "success", "danger"],
    );
    emit_enum(
        &mut out,
        "Interaction",
        &["single_select", "multi_select", "none"],
    );
    emit_enum(&mut out, "Connector", &["none", "dots_line", "arrow"]);
    emit_enum(
        &mut out,
        "TimelineStatus",
        &["completed", "active", "upcoming"],
    );
    emit_enum(&mut out, "EventSeverity", &["major", "minor", "info"]);
    emit_enum(&mut out, "EventFilter", &["all", "major"]);
    emit_enum(
        &mut out,
        "TreeStatus",
        &[
            "default",
            "completed",
            "active",
            "blocked",
            "priority",
            "upcoming",
        ],
    );
    emit_enum(
        &mut out,
        "TreeFilter",
        &["all", "incomplete", "blocked", "priority"],
    );
    emit_enum(
        &mut out,
        "ButtonVariant",
        &["primary", "secondary", "ghost"],
    );
    emit_enum(&mut out, "IconSize", &["xs", "sm", "md", "lg", "xl"]);
    emit_enum(&mut out, "AvatarSize", &["sm", "md", "lg", "xl"]);
    emit_enum(&mut out, "ChartKind", &["pie", "bar", "timeseries"]);
    emit_enum(&mut out, "ChartOrientation", &["vertical", "horizontal"]);
    emit_enum(&mut out, "PrintFlow", &["slides", "continuous", "square"]);
    emit_enum(
        &mut out,
        "Texture",
        &["none", "dots", "grid", "grain", "topography", "diagonal"],
    );
    emit_enum(&mut out, "Glow", &["none", "accent", "corner"]);
    emit_enum(&mut out, "NavLayout", &["top", "sidebar"]);
    emit_enum(&mut out, "Mode", &["dark", "light"]);
    emit_enum(
        &mut out,
        "AnnotationStatus",
        &["pending", "incorporated", "ignored", "stale"],
    );
    emit_enum(&mut out, "AnnotationSource", &["cli", "agent", "web"]);
    emit_enum(&mut out, "RefreshMode", &["human", "auto", "assisted"]);
    emit_enum(
        &mut out,
        "ThemeName",
        &[
            "dark", "light", "red", "orange", "yellow", "green", "blue", "indigo", "violet",
        ],
    );

    // Supporting types
    emit_interface(
        &mut out,
        "ThemeTokens",
        &[
            ("bg", "string"),
            ("surface", "string"),
            ("surface_strong", "string"),
            ("border", "string"),
            ("border_strong", "string"),
            ("accent", "string"),
            ("accent_soft", "string"),
            ("text", "string"),
            ("text_muted", "string"),
            ("text_subtle", "string"),
            ("overlay_hover", "string"),
            ("green", "string"),
            ("yellow", "string"),
            ("red", "string"),
            ("header_border", "string"),
        ],
    );
    emit_interface(
        &mut out,
        "MetaField",
        &[("key", "string"), ("value", "string")],
    );
    emit_interface(&mut out, "Link", &[("label", "string"), ("href", "string")]);
    emit_interface(
        &mut out,
        "Badge",
        &[("label", "string"), ("color?", "SemColor")],
    );
    emit_interface(
        &mut out,
        "Card",
        &[
            ("title", "string"),
            ("badge?", "Badge"),
            ("description?", "string"),
            ("links?", "Link[]"),
            ("href?", "string"),
            ("color?", "SemColor"),
        ],
    );
    emit_interface(
        &mut out,
        "SelectableCard",
        &[
            ("title", "string"),
            ("eyebrow?", "string"),
            ("bullets?", "string[]"),
            ("body?", "string"),
            ("color?", "SemColor"),
        ],
    );
    emit_interface(
        &mut out,
        "TimelineItem",
        &[("name", "string"), ("status", "TimelineStatus")],
    );
    emit_interface(
        &mut out,
        "Stat",
        &[
            ("label", "string"),
            ("value", "string"),
            ("detail?", "string"),
            ("color?", "SemColor"),
        ],
    );
    emit_interface(
        &mut out,
        "BeforeAfterItem",
        &[
            ("title", "string"),
            ("before", "string"),
            ("after", "string"),
            ("after_context?", "string"),
        ],
    );
    emit_interface(
        &mut out,
        "ComparePanel",
        &[
            ("eyebrow?", "string"),
            ("title", "string"),
            ("stats", "CompareStat[]"),
        ],
    );
    emit_interface(
        &mut out,
        "CompareStat",
        &[
            ("label", "string"),
            ("value", "string"),
            ("color?", "SemColor"),
        ],
    );
    emit_interface(
        &mut out,
        "Step",
        &[("title", "string"), ("detail?", "string")],
    );
    emit_interface(
        &mut out,
        "TableColumn",
        &[
            ("key", "string"),
            ("label", "string"),
            ("sortable?", "boolean"),
            ("align?", "Align"),
        ],
    );
    emit_interface(
        &mut out,
        "Tab",
        &[("label", "string"), ("components", "Component[]")],
    );
    emit_interface(
        &mut out,
        "AccordionItem",
        &[("title", "string"), ("components", "Component[]")],
    );
    emit_interface(
        &mut out,
        "EventItem",
        &[
            ("date", "string"),
            ("title", "string"),
            ("summary?", "string"),
            ("severity?", "EventSeverity"),
            ("source?", "string"),
            ("link?", "string"),
        ],
    );
    emit_interface(
        &mut out,
        "TreeNode",
        &[
            ("label", "string"),
            ("status?", "TreeStatus"),
            ("note?", "string"),
            ("children?", "TreeNode[]"),
        ],
    );
    emit_interface(
        &mut out,
        "VennSet",
        &[("label", "string"), ("color?", "SemColor")],
    );
    emit_interface(
        &mut out,
        "VennOverlap",
        &[("sets", "number[]"), ("label?", "string")],
    );
    emit_interface(
        &mut out,
        "BreadcrumbItem",
        &[("label", "string"), ("href?", "string")],
    );
    emit_interface(
        &mut out,
        "ButtonConfig",
        &[
            ("label", "string"),
            ("href", "string"),
            ("variant?", "ButtonVariant"),
            ("external?", "boolean"),
            ("icon?", "string"),
        ],
    );
    emit_interface(
        &mut out,
        "DefinitionItem",
        &[("term", "string"), ("definition", "string")],
    );
    emit_interface(
        &mut out,
        "AvatarConfig",
        &[("name", "string"), ("src?", "string")],
    );
    emit_interface(
        &mut out,
        "EmptyStateAction",
        &[("label", "string"), ("href", "string")],
    );
    emit_interface(
        &mut out,
        "ChartPoint",
        &[
            ("label", "string"),
            ("value", "number"),
            ("color?", "SemColor"),
        ],
    );
    emit_interface(
        &mut out,
        "ChartSeries",
        &[
            ("label", "string"),
            ("color?", "SemColor"),
            ("points", "ChartPoint[]"),
        ],
    );
    emit_interface(
        &mut out,
        "ResourceItem",
        &[
            ("title", "string"),
            ("href", "string"),
            ("description?", "string"),
            ("owner?", "string"),
        ],
    );
    emit_interface(
        &mut out,
        "Slide",
        &[
            ("label", "string"),
            ("components", "Component[]"),
            ("hide_label?", "boolean"),
        ],
    );

    // Component union (tagged by "type")
    out.push_str("export type Component =\n");
    let components = vec![
        (
            "header",
            vec![
                ("title", "string"),
                ("subtitle?", "string"),
                ("eyebrow?", "string"),
                ("align?", "Align"),
                ("id?", "string"),
            ],
        ),
        (
            "hero_banner",
            vec![
                ("title", "string"),
                ("eyebrow?", "string"),
                ("subtitle?", "string"),
                ("buttons?", "ButtonConfig[]"),
            ],
        ),
        ("meta", vec![("fields", "MetaField[]")]),
        (
            "card_grid",
            vec![
                ("cards", "Card[]"),
                ("min_width?", "number"),
                ("connector?", "Connector"),
            ],
        ),
        (
            "selectable_grid",
            vec![
                ("cards", "SelectableCard[]"),
                ("interaction?", "Interaction"),
                ("connector?", "Connector"),
            ],
        ),
        ("timeline", vec![("items", "TimelineItem[]")]),
        (
            "stat_grid",
            vec![("stats", "Stat[]"), ("columns?", "number")],
        ),
        (
            "before_after",
            vec![
                ("items", "BeforeAfterItem[]"),
                ("before_label?", "string"),
                ("after_label?", "string"),
            ],
        ),
        (
            "split_compare",
            vec![("left", "ComparePanel"), ("right", "ComparePanel")],
        ),
        ("steps", vec![("items", "Step[]"), ("numbered?", "boolean")]),
        ("markdown", vec![("body", "string")]),
        (
            "table",
            vec![
                ("columns", "TableColumn[]"),
                ("rows", "Record<string, unknown>[]"),
                ("filterable?", "boolean"),
            ],
        ),
        (
            "callout",
            vec![
                ("variant?", "CalloutVariant"),
                ("title?", "string"),
                ("body", "string"),
                ("links?", "ButtonConfig[]"),
            ],
        ),
        ("code", vec![("language?", "string"), ("code", "string")]),
        ("tabs", vec![("tabs", "Tab[]")]),
        (
            "section",
            vec![
                ("heading?", "string"),
                ("eyebrow?", "string"),
                ("components", "Component[]"),
                ("align?", "Align"),
                ("id?", "string"),
            ],
        ),
        (
            "columns",
            vec![("columns", "Component[][]"), ("equal_heights?", "boolean")],
        ),
        ("accordion", vec![("items", "AccordionItem[]")]),
        (
            "event_timeline",
            vec![
                ("events", "EventItem[]"),
                ("default_filter?", "EventFilter"),
                ("show_filter_toggle?", "boolean"),
                ("limit?", "number"),
            ],
        ),
        (
            "tree",
            vec![
                ("nodes", "TreeNode[]"),
                ("default_filter?", "TreeFilter"),
                ("show_filter_toggle?", "boolean"),
                ("default_collapsed?", "boolean"),
            ],
        ),
        (
            "venn",
            vec![
                ("sets", "VennSet[]"),
                ("overlaps?", "VennOverlap[]"),
                ("title?", "string"),
            ],
        ),
        (
            "image",
            vec![
                ("src", "string"),
                ("alt?", "string"),
                ("caption?", "string"),
                ("max_width?", "number"),
                ("align?", "Align"),
            ],
        ),
        (
            "embed",
            vec![
                ("src", "string"),
                ("title?", "string"),
                ("aspect?", "string"),
            ],
        ),
        ("resources", vec![("items", "ResourceItem[]")]),
        ("badge", vec![("label", "string"), ("color?", "SemColor")]),
        ("tag", vec![("label", "string"), ("color?", "SemColor")]),
        ("divider", vec![("label?", "string")]),
        ("kbd", vec![("keys", "string[]")]),
        ("status", vec![("label", "string"), ("color?", "SemColor")]),
        ("breadcrumb", vec![("items", "BreadcrumbItem[]")]),
        ("button_group", vec![("buttons", "ButtonConfig[]")]),
        ("definition_list", vec![("items", "DefinitionItem[]")]),
        (
            "blockquote",
            vec![("body", "string"), ("attribution?", "string")],
        ),
        (
            "avatar",
            vec![
                ("name", "string"),
                ("src?", "string"),
                ("size?", "AvatarSize"),
                ("subtitle?", "string"),
            ],
        ),
        (
            "avatar_group",
            vec![
                ("avatars", "AvatarConfig[]"),
                ("size?", "AvatarSize"),
                ("max?", "number"),
            ],
        ),
        (
            "progress_bar",
            vec![
                ("value", "number"),
                ("label?", "string"),
                ("color?", "SemColor"),
                ("detail?", "string"),
            ],
        ),
        (
            "empty_state",
            vec![
                ("title", "string"),
                ("body?", "string"),
                ("action?", "EmptyStateAction"),
                ("icon?", "string"),
            ],
        ),
        (
            "icon",
            vec![
                ("name", "string"),
                ("size?", "IconSize"),
                ("color?", "SemColor"),
            ],
        ),
        (
            "chart",
            vec![
                ("kind", "ChartKind"),
                ("title?", "string"),
                ("height?", "number"),
                ("x_label?", "string"),
                ("y_label?", "string"),
                ("orientation?", "ChartOrientation"),
                ("data?", "ChartPoint[]"),
                ("series?", "ChartSeries[]"),
            ],
        ),
        ("role_map", vec![("title?", "string")]),
    ];

    for (i, (tag, fields)) in components.iter().enumerate() {
        out.push_str("  | { type: \"");
        out.push_str(tag);
        out.push('"');
        for (name, ts_type) in fields {
            out.push_str("; ");
            out.push_str(name);
            out.push_str(": ");
            out.push_str(ts_type);
        }
        out.push_str(" }");
        if i < components.len() - 1 {
            out.push('\n');
        }
    }
    out.push_str(";\n\n");

    // Freshness types
    emit_interface(
        &mut out,
        "SourceOfTruth",
        &[("label", "string"), ("href?", "string")],
    );
    emit_interface(
        &mut out,
        "RefreshStep",
        &[
            ("run?", "string"),
            ("prompt?", "string"),
            ("review?", "string"),
        ],
    );
    emit_interface(
        &mut out,
        "RefreshConfig",
        &[("mode?", "RefreshMode"), ("steps?", "RefreshStep[]")],
    );
    emit_interface(
        &mut out,
        "Freshness",
        &[
            ("updated?", "string"),
            ("review_every?", "string"),
            ("owner?", "string"),
            ("sources_of_truth?", "(string | SourceOfTruth)[]"),
            ("expires?", "string"),
            ("refresh?", "string | RefreshConfig"),
        ],
    );
    emit_interface(
        &mut out,
        "Reference",
        &[("url", "string"), ("note?", "string")],
    );

    // Nav / Site config
    emit_interface(
        &mut out,
        "NavLink",
        &[
            ("label", "string"),
            ("href?", "string"),
            ("children?", "NavLink[]"),
            ("personas?", "string[]"),
            ("collapsed?", "boolean"),
        ],
    );
    emit_interface(
        &mut out,
        "Voice",
        &[
            ("tone?", "string"),
            ("reading_level?", "string"),
            (
                "terminology?",
                "{ prefer?: Record<string, string>; avoid?: string[] }",
            ),
        ],
    );
    emit_interface(
        &mut out,
        "Role",
        &[
            ("id", "string"),
            ("label", "string"),
            ("description?", "string"),
            ("icon?", "string"),
            ("href?", "string"),
        ],
    );
    emit_interface(
        &mut out,
        "DriftRepo",
        &[("prefix", "string"), ("local?", "string")],
    );
    emit_interface(&mut out, "DriftConfig", &[("repos", "DriftRepo[]")]);

    // Page
    out.push_str("export interface Page {\n");
    out.push_str("  title: string;\n");
    out.push_str("  shell: Shell;\n");
    out.push_str("  eyebrow?: string;\n");
    out.push_str("  subtitle?: string;\n");
    out.push_str("  components?: Component[];\n");
    out.push_str("  slides?: Slide[];\n");
    out.push_str("  unlisted?: boolean;\n");
    out.push_str("  texture?: Texture;\n");
    out.push_str("  glow?: Glow;\n");
    out.push_str("  print_flow?: PrintFlow;\n");
    out.push_str("  search_terms?: string[];\n");
    out.push_str("  freshness?: \"never\" | Freshness;\n");
    out.push_str("  owner?: string;\n");
    out.push_str("  references?: Reference[];\n");
    out.push_str("  personas?: string[];\n");
    out.push_str("  archived?: boolean;\n");
    out.push_str("  draft?: boolean;\n");
    out.push_str("  nav_layout?: NavLayout;\n");
    out.push_str("  nav?: NavLink[];\n");
    out.push_str("}\n\n");

    // SiteConfig
    out.push_str("export interface SiteConfig {\n");
    out.push_str("  name: string;\n");
    out.push_str("  theme?: string;\n");
    out.push_str("  colors?: Record<string, string>;\n");
    out.push_str("  nav?: NavLink[];\n");
    out.push_str("  favicon?: string | { svg?: string; png?: string; ico?: string; apple_touch_icon?: string };\n");
    out.push_str("  logo?: string | { src: string; height?: string; alt?: string };\n");
    out.push_str("  view_source?: boolean;\n");
    out.push_str("  texture?: Texture;\n");
    out.push_str("  glow?: Glow;\n");
    out.push_str("  nav_layout?: NavLayout;\n");
    out.push_str("  mode?: Mode;\n");
    out.push_str("  description?: string;\n");
    out.push_str("  url?: string;\n");
    out.push_str("  edit_url?: string;\n");
    out.push_str("  og_image?: string;\n");
    out.push_str("  voice?: Voice;\n");
    out.push_str("  roles?: Role[];\n");
    out.push_str("  drift?: DriftConfig;\n");
    out.push_str("}\n\n");

    // ValidationError
    emit_interface(
        &mut out,
        "ValidationError",
        &[
            ("file", "string"),
            ("path", "string"),
            ("error_type", "string"),
            ("message", "string"),
            ("suggestion?", "string"),
        ],
    );

    // Annotation
    emit_interface(
        &mut out,
        "Annotation",
        &[
            ("id", "string"),
            ("text", "string"),
            ("author", "string"),
            ("section?", "string"),
            ("added", "string"),
            ("status", "AnnotationStatus"),
            ("source", "AnnotationSource"),
        ],
    );

    out
}

pub fn emit_react() -> Result<()> {
    print!("{}", generate_react());
    Ok(())
}

fn generate_react() -> String {
    r##"// Auto-generated by `kazam sdk emit-react` — do not edit
/* eslint-disable @next/next/no-img-element */

interface PageData {
  title: string;
  subtitle?: string;
  shell?: string;
  components?: ComponentData[];
}

interface ComponentData {
  type: string;
  [key: string]: unknown;
}

interface PageRendererProps {
  page: PageData;
  renderMarkdown?: (md: string) => string;
}

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function ComponentView({
  comp,
  index,
  renderMarkdown,
}: {
  comp: ComponentData;
  index: number;
  renderMarkdown?: (md: string) => string;
}) {
  const id = (comp.id as string) || `c-${index}`;
  const md = (s: string) =>
    renderMarkdown ? (
      <div dangerouslySetInnerHTML={{ __html: renderMarkdown(s) }} />
    ) : (
      <p>{s}</p>
    );

  switch (comp.type) {
    case "header": {
      const title = (comp.title as string) || "";
      const subtitle = comp.subtitle as string | undefined;
      const eyebrow = comp.eyebrow as string | undefined;
      return (
        <div id={id} className="c-header">
          {eyebrow && <div className="c-header-eyebrow">{eyebrow}</div>}
          <h1 className="c-header-title">{title}</h1>
          {subtitle && <p className="c-header-subtitle">{subtitle}</p>}
        </div>
      );
    }

    case "markdown": {
      const body = (comp.body as string) || "";
      return <div id={id} className="c-markdown">{md(body)}</div>;
    }

    case "callout": {
      const variant = (comp.variant as string) || "info";
      const title = comp.title as string | undefined;
      const body = (comp.body as string) || "";
      return (
        <div id={id} className={`c-callout c-callout-${variant}`}>
          {title && <div className="c-callout-title">{title}</div>}
          <div className="c-callout-body c-markdown">{md(body)}</div>
        </div>
      );
    }

    case "card_grid": {
      const cards = (comp.cards as Array<{
        title: string;
        description?: string;
        badge?: { label: string; color?: string };
        href?: string;
      }>) || [];
      return (
        <div id={id} className="c-card-grid">
          {cards.map((card, i) => {
            const Tag = card.href ? "a" : "div";
            return (
              <Tag key={i} className="c-card c-card-default" {...(card.href ? { href: card.href } : {})}>
                <div className="c-card-top">
                  <h2 className="c-card-title">{card.title}</h2>
                  {card.badge && (
                    <span className={`c-badge c-badge-${card.badge.color || "default"}`}>
                      {card.badge.label}
                    </span>
                  )}
                </div>
                {card.description && <p className="c-card-desc">{card.description}</p>}
              </Tag>
            );
          })}
        </div>
      );
    }

    case "stat_grid": {
      const stats = (comp.stats as Array<{
        label: string;
        value: string;
        detail?: string;
        color?: string;
      }>) || [];
      const columns = (comp.columns as number) || stats.length;
      return (
        <div
          id={id}
          className="c-stat-grid"
          style={{ gridTemplateColumns: `repeat(${columns}, 1fr)` }}
        >
          {stats.map((s, i) => (
            <div key={i} className="c-stat">
              <div className="c-stat-label">{s.label}</div>
              <div className="c-stat-value">{s.value}</div>
              {s.detail && <div className="c-stat-detail">{s.detail}</div>}
            </div>
          ))}
        </div>
      );
    }

    case "steps": {
      const items = (comp.items as Array<{ title: string; detail?: string }>) || [];
      const numbered = comp.numbered !== false;
      const Tag = numbered ? "ol" : "ul";
      return (
        <Tag id={id} className="c-steps">
          {items.map((item, i) => (
            <li key={i} className="c-step">
              {numbered ? (
                <div className="c-step-num">{i + 1}</div>
              ) : (
                <div className="c-step-bullet" />
              )}
              <div>
                <div className="c-step-title">{item.title}</div>
                {item.detail && <div className="c-step-detail">{item.detail}</div>}
              </div>
            </li>
          ))}
        </Tag>
      );
    }

    case "code": {
      const code = (comp.code as string) || "";
      const language = comp.language as string | undefined;
      return (
        <pre id={id} className="c-code" {...(language ? { "data-lang": language } : {})}>
          <code>{code}</code>
        </pre>
      );
    }

    case "image": {
      const src = (comp.src as string) || "";
      const alt = (comp.alt as string) || "";
      const caption = comp.caption as string | undefined;
      return (
        <figure id={id} className="c-image">
          <img src={src} alt={alt} />
          {caption && <figcaption>{caption}</figcaption>}
        </figure>
      );
    }

    case "divider": {
      const label = comp.label as string | undefined;
      if (label) {
        return (
          <div id={id} className="c-divider c-divider-labeled">
            <span className="c-divider-line" />
            <span className="c-divider-label">{label}</span>
            <span className="c-divider-line" />
          </div>
        );
      }
      return <hr id={id} className="c-divider" />;
    }

    case "table": {
      const columns = (comp.columns as Array<{ key: string; label: string }>) || [];
      const rows = (comp.rows as Array<Record<string, unknown>>) || [];
      return (
        <div id={id} className="c-table-wrap">
          <table className="c-table">
            <thead>
              <tr>
                {columns.map((col, i) => (
                  <th key={i}>{col.label}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {rows.map((row, ri) => (
                <tr key={ri}>
                  {columns.map((col, ci) => (
                    <td key={ci}>{String(row[col.key] ?? "")}</td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      );
    }

    case "meta": {
      const fields = (comp.fields as Array<{ key: string; value: string }>) || [];
      return (
        <div id={id} className="c-meta">
          {fields.map((f, i) => (
            <div key={i} className="c-meta-item">
              <span className="c-meta-key">{f.key}</span>
              <span className="c-meta-value">{f.value}</span>
            </div>
          ))}
        </div>
      );
    }

    case "section": {
      const heading = comp.heading as string | undefined;
      const eyebrow = comp.eyebrow as string | undefined;
      const children = (comp.components as ComponentData[]) || [];
      return (
        <section id={id} className="c-section">
          {(eyebrow || heading) && (
            <div className="c-section-header">
              {eyebrow && <div className="c-section-eyebrow">{eyebrow}</div>}
              {heading && <h2 className="c-section-heading">{heading}</h2>}
            </div>
          )}
          {children.map((c, i) => (
            <ComponentView key={i} comp={c} index={i} renderMarkdown={renderMarkdown} />
          ))}
        </section>
      );
    }

    case "blockquote": {
      const body = (comp.body as string) || "";
      const attribution = comp.attribution as string | undefined;
      return (
        <figure id={id} className="c-blockquote">
          <blockquote><p>{body}</p></blockquote>
          {attribution && (
            <figcaption className="c-blockquote-attribution">— {attribution}</figcaption>
          )}
        </figure>
      );
    }

    case "badge": {
      const label = (comp.label as string) || "";
      const color = (comp.color as string) || "default";
      return <span id={id} className={`c-badge c-badge-${color}`}>{label}</span>;
    }

    case "status": {
      const label = (comp.label as string) || "";
      const color = (comp.color as string) || "default";
      return (
        <span id={id} className={`c-status c-status-${color}`}>
          <span className="c-status-dot" />
          <span>{label}</span>
        </span>
      );
    }

    case "progress_bar": {
      const value = Math.min(100, (comp.value as number) || 0);
      const label = comp.label as string | undefined;
      const color = (comp.color as string) || "default";
      const detail = comp.detail as string | undefined;
      return (
        <div id={id} className="c-progress">
          {(label || true) && (
            <div className="c-progress-labels">
              {label ? <span className="c-progress-label">{label}</span> : <span />}
              <span className="c-progress-value">{value}%</span>
            </div>
          )}
          <div className="c-progress-track" role="progressbar" aria-valuenow={value} aria-valuemin={0} aria-valuemax={100}>
            <div className={`c-progress-fill c-progress-fill-${color}`} style={{ width: `${value}%` }} />
          </div>
          {detail && <div className="c-progress-detail">{detail}</div>}
        </div>
      );
    }

    case "embed": {
      const src = (comp.src as string) || "";
      const title = (comp.title as string) || "Embedded video";
      const aspect = (comp.aspect as string) || "16/9";
      return (
        <div id={id} className="c-embed" style={{ aspectRatio: aspect }}>
          <iframe src={src} title={title} frameBorder="0" allowFullScreen />
        </div>
      );
    }

    case "timeline": {
      const items = (comp.items as Array<{ name: string; status: string }>) || [];
      return (
        <div id={id} className="c-timeline">
          {items.map((item, i) => (
            <div key={i} className={`c-timeline-item c-timeline-${item.status || "upcoming"}`}>
              <div className="c-timeline-marker" />
              {i < items.length - 1 && <div className="c-timeline-connector" />}
              <div className="c-timeline-label">{item.name}</div>
            </div>
          ))}
        </div>
      );
    }

    case "split_compare": {
      const left = comp.left as { eyebrow?: string; title: string; stats: Array<{ label: string; value: string; color?: string }> };
      const right = comp.right as { eyebrow?: string; title: string; stats: Array<{ label: string; value: string; color?: string }> };
      return (
        <div id={id} className="c-split-compare">
          {[left, right].map((panel, pi) => (
            <div key={pi} className={`c-split-panel c-split-panel-${pi === 0 ? "left" : "right"}`}>
              {panel.eyebrow && <div className="c-split-eyebrow">{panel.eyebrow}</div>}
              <h3 className="c-split-title">{panel.title}</h3>
              <div className="c-split-stats">
                {(panel.stats || []).map((s, si) => (
                  <div key={si} className="c-split-stat">
                    <span className="c-split-stat-label">{s.label}</span>
                    <span className={`c-split-stat-value c-color-${s.color || "default"}`}>{s.value}</span>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      );
    }

    case "before_after": {
      const items = (comp.items as Array<{ title: string; before: string; after: string; after_context?: string }>) || [];
      const beforeLabel = (comp.before_label as string) || "Before";
      const afterLabel = (comp.after_label as string) || "After";
      return (
        <div id={id} className="c-before-after">
          {items.map((item, i) => (
            <div key={i} className="c-ba-item">
              <h3 className="c-ba-title">{item.title}</h3>
              <div className="c-ba-panels">
                <div className="c-ba-panel c-ba-before">
                  <div className="c-ba-label">{beforeLabel}</div>
                  <p>{item.before}</p>
                </div>
                <div className="c-ba-panel c-ba-after">
                  <div className="c-ba-label">{afterLabel}</div>
                  <p>{item.after}</p>
                  {item.after_context && <div className="c-ba-context">{item.after_context}</div>}
                </div>
              </div>
            </div>
          ))}
        </div>
      );
    }

    case "tabs": {
      const tabs = (comp.tabs as Array<{ label: string; components: ComponentData[] }>) || [];
      return (
        <div id={id} className="c-tabs">
          {tabs.map((tab, ti) => (
            <details key={ti} className="c-tab" {...(ti === 0 ? { open: true } : {})}>
              <summary className="c-tab-label">{tab.label}</summary>
              <div className="c-tab-content">
                {(tab.components || []).map((c, ci) => (
                  <ComponentView key={ci} comp={c} index={ci} renderMarkdown={renderMarkdown} />
                ))}
              </div>
            </details>
          ))}
        </div>
      );
    }

    case "columns": {
      const cols = (comp.columns as ComponentData[][]) || [];
      return (
        <div id={id} className="c-columns" style={{ gridTemplateColumns: `repeat(${cols.length}, 1fr)` }}>
          {cols.map((col, ci) => (
            <div key={ci} className="c-column">
              {col.map((c, i) => (
                <ComponentView key={i} comp={c} index={i} renderMarkdown={renderMarkdown} />
              ))}
            </div>
          ))}
        </div>
      );
    }

    case "accordion": {
      const items = (comp.items as Array<{ title: string; components: ComponentData[] }>) || [];
      return (
        <div id={id} className="c-accordion">
          {items.map((item, i) => (
            <details key={i} className="c-accordion-item">
              <summary className="c-accordion-title">{item.title}</summary>
              <div className="c-accordion-content">
                {(item.components || []).map((c, ci) => (
                  <ComponentView key={ci} comp={c} index={ci} renderMarkdown={renderMarkdown} />
                ))}
              </div>
            </details>
          ))}
        </div>
      );
    }

    case "hero_banner": {
      const title = (comp.title as string) || "";
      const eyebrow = comp.eyebrow as string | undefined;
      const subtitle = comp.subtitle as string | undefined;
      const buttons = (comp.buttons as Array<{ label: string; href: string; variant?: string; external?: boolean }>) || [];
      return (
        <div id={id} className="c-hero-banner">
          {eyebrow && <div className="c-hero-eyebrow">{eyebrow}</div>}
          <h1 className="c-hero-title">{title}</h1>
          {subtitle && <p className="c-hero-subtitle">{subtitle}</p>}
          {buttons.length > 0 && (
            <div className="c-hero-buttons">
              {buttons.map((b, i) => (
                <a key={i} className={`c-btn c-btn-${b.variant || "primary"}`} href={b.href}>{b.label}</a>
              ))}
            </div>
          )}
        </div>
      );
    }

    case "event_timeline": {
      const events = (comp.events as Array<{ date: string; title: string; summary?: string; severity?: string; source?: string; link?: string }>) || [];
      return (
        <div id={id} className="c-event-timeline">
          {events.map((ev, i) => (
            <div key={i} className={`c-event c-event-${ev.severity || "minor"}`}>
              <div className="c-event-date">{ev.date}</div>
              <div className="c-event-body">
                <div className="c-event-title">{ev.link ? <a href={ev.link}>{ev.title}</a> : ev.title}</div>
                {ev.summary && <p className="c-event-summary">{ev.summary}</p>}
                {ev.source && <span className="c-event-source">{ev.source}</span>}
              </div>
            </div>
          ))}
        </div>
      );
    }

    case "tree": {
      const nodes = (comp.nodes as Array<Record<string, unknown>>) || [];
      const renderNode = (node: Record<string, unknown>, depth: number): JSX.Element => {
        const children = (node.children as Array<Record<string, unknown>>) || [];
        return (
          <div className={`c-tree-node c-tree-${(node.status as string) || "default"}`} style={{ paddingLeft: `${depth * 20}px` }}>
            <div className="c-tree-label">
              <span className="c-tree-marker" />
              <span>{node.label as string}</span>
              {node.note && <span className="c-tree-note">{node.note as string}</span>}
            </div>
            {children.map((child, i) => <div key={i}>{renderNode(child, depth + 1)}</div>)}
          </div>
        );
      };
      return <div id={id} className="c-tree">{nodes.map((n, i) => <div key={i}>{renderNode(n, 0)}</div>)}</div>;
    }

    case "selectable_grid": {
      const cards = (comp.cards as Array<{ title: string; eyebrow?: string; bullets?: string[]; body?: string }>) || [];
      const connector = comp.connector as string | undefined;
      return (
        <div id={id} className={`c-selectable-grid ${connector === "dots_line" ? "c-connector-dots" : ""}`}>
          {cards.map((card, i) => (
            <div key={i} className="c-selectable-card">
              {card.eyebrow && <div className="c-selectable-eyebrow">{card.eyebrow}</div>}
              <h3 className="c-selectable-title">{card.title}</h3>
              {card.body && <p>{card.body}</p>}
              {card.bullets && (
                <ul className="c-selectable-bullets">
                  {card.bullets.map((b, bi) => <li key={bi}>{b}</li>)}
                </ul>
              )}
            </div>
          ))}
        </div>
      );
    }

    case "resources": {
      const items = (comp.items as Array<{ title: string; href: string; description?: string; owner?: string }>) || [];
      return (
        <div id={id} className="c-resources">
          {items.map((item, i) => (
            <a key={i} className="c-resource" href={item.href}>
              <div className="c-resource-title">{item.title}</div>
              {item.description && <div className="c-resource-desc">{item.description}</div>}
              {item.owner && <div className="c-resource-owner">{item.owner}</div>}
            </a>
          ))}
        </div>
      );
    }

    case "button_group": {
      const buttons = (comp.buttons as Array<{ label: string; href: string; variant?: string; external?: boolean }>) || [];
      return (
        <div id={id} className="c-button-group">
          {buttons.map((b, i) => (
            <a key={i} className={`c-btn c-btn-${b.variant || "primary"}`} href={b.href} {...(b.external ? { target: "_blank", rel: "noopener noreferrer" } : {})}>{b.label}</a>
          ))}
        </div>
      );
    }

    case "definition_list": {
      const items = (comp.items as Array<{ term: string; definition: string }>) || [];
      return (
        <dl id={id} className="c-definition-list">
          {items.map((item, i) => (
            <div key={i} className="c-dl-item">
              <dt>{item.term}</dt>
              <dd>{item.definition}</dd>
            </div>
          ))}
        </dl>
      );
    }

    case "avatar": {
      const name = (comp.name as string) || "";
      const src = comp.src as string | undefined;
      const subtitle = comp.subtitle as string | undefined;
      const initials = name.split(" ").map(w => w[0]).join("").slice(0, 2).toUpperCase();
      return (
        <div id={id} className={`c-avatar c-avatar-${(comp.size as string) || "md"}`}>
          {src ? <img src={src} alt={name} className="c-avatar-img" /> : <div className="c-avatar-initials">{initials}</div>}
          <div className="c-avatar-info">
            <div className="c-avatar-name">{name}</div>
            {subtitle && <div className="c-avatar-subtitle">{subtitle}</div>}
          </div>
        </div>
      );
    }

    case "avatar_group": {
      const avatars = (comp.avatars as Array<{ name: string; src?: string }>) || [];
      const max = (comp.max as number) || 5;
      const visible = avatars.slice(0, max);
      const overflow = avatars.length - max;
      return (
        <div id={id} className="c-avatar-group">
          {visible.map((a, i) => {
            const initials = a.name.split(" ").map(w => w[0]).join("").slice(0, 2).toUpperCase();
            return a.src
              ? <img key={i} src={a.src} alt={a.name} className="c-avatar-circle" title={a.name} />
              : <div key={i} className="c-avatar-circle c-avatar-circle-initials" title={a.name}>{initials}</div>;
          })}
          {overflow > 0 && <div className="c-avatar-circle c-avatar-overflow">+{overflow}</div>}
        </div>
      );
    }

    case "breadcrumb": {
      const items = (comp.items as Array<{ label: string; href?: string }>) || [];
      return (
        <nav id={id} className="c-breadcrumb">
          {items.map((item, i) => (
            <span key={i}>
              {i > 0 && <span className="c-breadcrumb-sep">/</span>}
              {item.href ? <a href={item.href}>{item.label}</a> : <span>{item.label}</span>}
            </span>
          ))}
        </nav>
      );
    }

    case "tag": {
      const label = (comp.label as string) || "";
      const color = (comp.color as string) || "default";
      return <span id={id} className={`c-tag c-tag-${color}`}>{label}</span>;
    }

    case "kbd": {
      const keys = (comp.keys as string[]) || [];
      return (
        <span id={id} className="c-kbd">
          {keys.map((k, i) => (
            <span key={i}>
              {i > 0 && <span className="c-kbd-sep">+</span>}
              <kbd>{k}</kbd>
            </span>
          ))}
        </span>
      );
    }

    case "empty_state": {
      const title = (comp.title as string) || "";
      const body = comp.body as string | undefined;
      const action = comp.action as { label: string; href: string } | undefined;
      return (
        <div id={id} className="c-empty-state">
          <h3 className="c-empty-title">{title}</h3>
          {body && <p className="c-empty-body">{body}</p>}
          {action && <a className="c-btn c-btn-primary" href={action.href}>{action.label}</a>}
        </div>
      );
    }

    case "venn": {
      const sets = (comp.sets as Array<{ label: string; color?: string }>) || [];
      const overlaps = (comp.overlaps as Array<{ sets: number[]; label?: string }>) || [];
      const title = comp.title as string | undefined;
      return (
        <div id={id} className="c-venn">
          {title && <h3 className="c-venn-title">{title}</h3>}
          <div className="c-venn-diagram">
            {sets.map((s, i) => (
              <div key={i} className={`c-venn-set c-venn-set-${i} c-venn-color-${s.color || "default"}`}>
                <span>{s.label}</span>
              </div>
            ))}
          </div>
          {overlaps.length > 0 && (
            <div className="c-venn-overlaps">
              {overlaps.map((o, i) => o.label && (
                <div key={i} className="c-venn-overlap">
                  {sets.filter((_, si) => o.sets.includes(si)).map(s => s.label).join(" ∩ ")}: {o.label}
                </div>
              ))}
            </div>
          )}
        </div>
      );
    }

    case "chart": {
      const title = comp.title as string | undefined;
      const kind = (comp.kind as string) || "bar";
      return (
        <div id={id} className="c-chart" data-kind={kind}>
          {title && <h3 className="c-chart-title">{title}</h3>}
          <div className="c-chart-placeholder">Chart ({kind})</div>
        </div>
      );
    }

    case "role_map": {
      const title = comp.title as string | undefined;
      return (
        <div id={id} className="c-role-map">
          {title && <h3 className="c-role-map-title">{title}</h3>}
          <div className="c-role-map-placeholder">Roles configured in site settings</div>
        </div>
      );
    }

    default:
      return (
        <div id={id} className="c-unsupported" data-type={comp.type}>
          <em>Unsupported component: {comp.type}</em>
        </div>
      );
  }
}

export function PageRenderer({ page, renderMarkdown }: PageRendererProps) {
  const components = page.components ?? [];
  return (
    <div>
      {components.map((comp, i) => (
        <ComponentView key={i} comp={comp} index={i} renderMarkdown={renderMarkdown} />
      ))}
    </div>
  );
}

export { ComponentView, type PageData, type ComponentData, type PageRendererProps };
"##
    .to_string()
}

fn emit_enum(out: &mut String, name: &str, variants: &[&str]) {
    out.push_str("export type ");
    out.push_str(name);
    out.push_str(" = ");
    for (i, v) in variants.iter().enumerate() {
        if i > 0 {
            out.push_str(" | ");
        }
        out.push('"');
        out.push_str(v);
        out.push('"');
    }
    out.push_str(";\n\n");
}

fn emit_interface(out: &mut String, name: &str, fields: &[(&str, &str)]) {
    out.push_str("export interface ");
    out.push_str(name);
    out.push_str(" {\n");
    for (name, ts_type) in fields {
        if let Some(stripped) = name.strip_suffix('?') {
            out.push_str("  ");
            out.push_str(stripped);
            out.push_str("?: ");
        } else {
            out.push_str("  ");
            out.push_str(name);
            out.push_str(": ");
        }
        out.push_str(ts_type);
        out.push_str(";\n");
    }
    out.push_str("}\n\n");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn typescript_output_contains_key_types() {
        let ts = generate_typescript();
        assert!(ts.contains("export type Shell ="));
        assert!(ts.contains("export interface Page {"));
        assert!(ts.contains("export interface SiteConfig {"));
        assert!(ts.contains("export type Component ="));
        assert!(ts.contains("export interface ValidationError {"));
        assert!(ts.contains("{ type: \"header\""));
        assert!(ts.contains("{ type: \"chart\""));
        assert!(ts.contains("{ type: \"role_map\""));
    }
}
