use anyhow::Result;

pub fn emit_typescript() -> Result<()> {
    print!("{}", generate_typescript());
    Ok(())
}

fn generate_typescript() -> String {
    let mut out = String::with_capacity(8192);
    out.push_str("// Auto-generated by `kazam sdk emit` — do not edit\n\n");

    // Enums
    emit_enum(&mut out, "Shell", &["standard", "document", "deck"]);
    emit_enum(&mut out, "Align", &["left", "right", "center"]);
    emit_enum(
        &mut out,
        "SemColor",
        &["default", "green", "yellow", "red", "teal"],
    );
    emit_enum(
        &mut out,
        "CalloutVariant",
        &["info", "warn", "success", "danger"],
    );
    emit_enum(
        &mut out,
        "Interaction",
        &["single_select", "multi_select", "none"],
    );
    emit_enum(&mut out, "Connector", &["none", "dots_line", "arrow"]);
    emit_enum(
        &mut out,
        "TimelineStatus",
        &["completed", "active", "upcoming"],
    );
    emit_enum(&mut out, "EventSeverity", &["major", "minor", "info"]);
    emit_enum(&mut out, "EventFilter", &["all", "major"]);
    emit_enum(
        &mut out,
        "TreeStatus",
        &[
            "default",
            "completed",
            "active",
            "blocked",
            "priority",
            "upcoming",
        ],
    );
    emit_enum(
        &mut out,
        "TreeFilter",
        &["all", "incomplete", "blocked", "priority"],
    );
    emit_enum(
        &mut out,
        "ButtonVariant",
        &["primary", "secondary", "ghost"],
    );
    emit_enum(&mut out, "IconSize", &["xs", "sm", "md", "lg", "xl"]);
    emit_enum(&mut out, "AvatarSize", &["sm", "md", "lg", "xl"]);
    emit_enum(&mut out, "ChartKind", &["pie", "bar", "timeseries"]);
    emit_enum(&mut out, "ChartOrientation", &["vertical", "horizontal"]);
    emit_enum(&mut out, "PrintFlow", &["slides", "continuous", "square"]);
    emit_enum(
        &mut out,
        "Texture",
        &["none", "dots", "grid", "grain", "topography", "diagonal"],
    );
    emit_enum(&mut out, "Glow", &["none", "accent", "corner"]);
    emit_enum(&mut out, "NavLayout", &["top", "sidebar"]);
    emit_enum(&mut out, "Mode", &["dark", "light"]);
    emit_enum(
        &mut out,
        "AnnotationStatus",
        &["pending", "incorporated", "ignored", "stale"],
    );
    emit_enum(&mut out, "AnnotationSource", &["cli", "agent", "web"]);
    emit_enum(&mut out, "RefreshMode", &["human", "auto", "assisted"]);

    // Supporting types
    emit_interface(
        &mut out,
        "MetaField",
        &[("key", "string"), ("value", "string")],
    );
    emit_interface(&mut out, "Link", &[("label", "string"), ("href", "string")]);
    emit_interface(
        &mut out,
        "Badge",
        &[("label", "string"), ("color?", "SemColor")],
    );
    emit_interface(
        &mut out,
        "Card",
        &[
            ("title", "string"),
            ("badge?", "Badge"),
            ("description?", "string"),
            ("links?", "Link[]"),
            ("href?", "string"),
            ("color?", "SemColor"),
        ],
    );
    emit_interface(
        &mut out,
        "SelectableCard",
        &[
            ("title", "string"),
            ("eyebrow?", "string"),
            ("bullets?", "string[]"),
            ("body?", "string"),
            ("color?", "SemColor"),
        ],
    );
    emit_interface(
        &mut out,
        "TimelineItem",
        &[("name", "string"), ("status", "TimelineStatus")],
    );
    emit_interface(
        &mut out,
        "Stat",
        &[
            ("label", "string"),
            ("value", "string"),
            ("detail?", "string"),
            ("color?", "SemColor"),
        ],
    );
    emit_interface(
        &mut out,
        "BeforeAfterItem",
        &[
            ("title", "string"),
            ("before", "string"),
            ("after", "string"),
            ("after_context?", "string"),
        ],
    );
    emit_interface(
        &mut out,
        "ComparePanel",
        &[
            ("eyebrow?", "string"),
            ("title", "string"),
            ("stats", "CompareStat[]"),
        ],
    );
    emit_interface(
        &mut out,
        "CompareStat",
        &[
            ("label", "string"),
            ("value", "string"),
            ("color?", "SemColor"),
        ],
    );
    emit_interface(
        &mut out,
        "Step",
        &[("title", "string"), ("detail?", "string")],
    );
    emit_interface(
        &mut out,
        "TableColumn",
        &[
            ("key", "string"),
            ("label", "string"),
            ("sortable?", "boolean"),
            ("align?", "Align"),
        ],
    );
    emit_interface(
        &mut out,
        "Tab",
        &[("label", "string"), ("components", "Component[]")],
    );
    emit_interface(
        &mut out,
        "AccordionItem",
        &[("title", "string"), ("components", "Component[]")],
    );
    emit_interface(
        &mut out,
        "EventItem",
        &[
            ("date", "string"),
            ("title", "string"),
            ("summary?", "string"),
            ("severity?", "EventSeverity"),
            ("source?", "string"),
            ("link?", "string"),
        ],
    );
    emit_interface(
        &mut out,
        "TreeNode",
        &[
            ("label", "string"),
            ("status?", "TreeStatus"),
            ("note?", "string"),
            ("children?", "TreeNode[]"),
        ],
    );
    emit_interface(
        &mut out,
        "VennSet",
        &[("label", "string"), ("color?", "SemColor")],
    );
    emit_interface(
        &mut out,
        "VennOverlap",
        &[("sets", "number[]"), ("label?", "string")],
    );
    emit_interface(
        &mut out,
        "BreadcrumbItem",
        &[("label", "string"), ("href?", "string")],
    );
    emit_interface(
        &mut out,
        "ButtonConfig",
        &[
            ("label", "string"),
            ("href", "string"),
            ("variant?", "ButtonVariant"),
            ("external?", "boolean"),
            ("icon?", "string"),
        ],
    );
    emit_interface(
        &mut out,
        "DefinitionItem",
        &[("term", "string"), ("definition", "string")],
    );
    emit_interface(
        &mut out,
        "AvatarConfig",
        &[("name", "string"), ("src?", "string")],
    );
    emit_interface(
        &mut out,
        "EmptyStateAction",
        &[("label", "string"), ("href", "string")],
    );
    emit_interface(
        &mut out,
        "ChartPoint",
        &[
            ("label", "string"),
            ("value", "number"),
            ("color?", "SemColor"),
        ],
    );
    emit_interface(
        &mut out,
        "ChartSeries",
        &[
            ("label", "string"),
            ("color?", "SemColor"),
            ("points", "ChartPoint[]"),
        ],
    );
    emit_interface(
        &mut out,
        "ResourceItem",
        &[
            ("title", "string"),
            ("href", "string"),
            ("description?", "string"),
            ("owner?", "string"),
        ],
    );
    emit_interface(
        &mut out,
        "Slide",
        &[
            ("label", "string"),
            ("components", "Component[]"),
            ("hide_label?", "boolean"),
        ],
    );

    // Component union (tagged by "type")
    out.push_str("export type Component =\n");
    let components = vec![
        (
            "header",
            vec![
                ("title", "string"),
                ("subtitle?", "string"),
                ("eyebrow?", "string"),
                ("align?", "Align"),
                ("id?", "string"),
            ],
        ),
        (
            "hero_banner",
            vec![
                ("title", "string"),
                ("eyebrow?", "string"),
                ("subtitle?", "string"),
                ("buttons?", "ButtonConfig[]"),
            ],
        ),
        ("meta", vec![("fields", "MetaField[]")]),
        (
            "card_grid",
            vec![
                ("cards", "Card[]"),
                ("min_width?", "number"),
                ("connector?", "Connector"),
            ],
        ),
        (
            "selectable_grid",
            vec![
                ("cards", "SelectableCard[]"),
                ("interaction?", "Interaction"),
                ("connector?", "Connector"),
            ],
        ),
        ("timeline", vec![("items", "TimelineItem[]")]),
        (
            "stat_grid",
            vec![("stats", "Stat[]"), ("columns?", "number")],
        ),
        (
            "before_after",
            vec![
                ("items", "BeforeAfterItem[]"),
                ("before_label?", "string"),
                ("after_label?", "string"),
            ],
        ),
        (
            "split_compare",
            vec![("left", "ComparePanel"), ("right", "ComparePanel")],
        ),
        ("steps", vec![("items", "Step[]"), ("numbered?", "boolean")]),
        ("markdown", vec![("body", "string")]),
        (
            "table",
            vec![
                ("columns", "TableColumn[]"),
                ("rows", "Record<string, unknown>[]"),
                ("filterable?", "boolean"),
            ],
        ),
        (
            "callout",
            vec![
                ("variant?", "CalloutVariant"),
                ("title?", "string"),
                ("body", "string"),
                ("links?", "ButtonConfig[]"),
            ],
        ),
        ("code", vec![("language?", "string"), ("code", "string")]),
        ("tabs", vec![("tabs", "Tab[]")]),
        (
            "section",
            vec![
                ("heading?", "string"),
                ("eyebrow?", "string"),
                ("components", "Component[]"),
                ("align?", "Align"),
                ("id?", "string"),
            ],
        ),
        (
            "columns",
            vec![("columns", "Component[][]"), ("equal_heights?", "boolean")],
        ),
        ("accordion", vec![("items", "AccordionItem[]")]),
        (
            "event_timeline",
            vec![
                ("events", "EventItem[]"),
                ("default_filter?", "EventFilter"),
                ("show_filter_toggle?", "boolean"),
                ("limit?", "number"),
            ],
        ),
        (
            "tree",
            vec![
                ("nodes", "TreeNode[]"),
                ("default_filter?", "TreeFilter"),
                ("show_filter_toggle?", "boolean"),
                ("default_collapsed?", "boolean"),
            ],
        ),
        (
            "venn",
            vec![
                ("sets", "VennSet[]"),
                ("overlaps?", "VennOverlap[]"),
                ("title?", "string"),
            ],
        ),
        (
            "image",
            vec![
                ("src", "string"),
                ("alt?", "string"),
                ("caption?", "string"),
                ("max_width?", "number"),
                ("align?", "Align"),
            ],
        ),
        (
            "embed",
            vec![
                ("src", "string"),
                ("title?", "string"),
                ("aspect?", "string"),
            ],
        ),
        ("resources", vec![("items", "ResourceItem[]")]),
        ("badge", vec![("label", "string"), ("color?", "SemColor")]),
        ("tag", vec![("label", "string"), ("color?", "SemColor")]),
        ("divider", vec![("label?", "string")]),
        ("kbd", vec![("keys", "string[]")]),
        ("status", vec![("label", "string"), ("color?", "SemColor")]),
        ("breadcrumb", vec![("items", "BreadcrumbItem[]")]),
        ("button_group", vec![("buttons", "ButtonConfig[]")]),
        ("definition_list", vec![("items", "DefinitionItem[]")]),
        (
            "blockquote",
            vec![("body", "string"), ("attribution?", "string")],
        ),
        (
            "avatar",
            vec![
                ("name", "string"),
                ("src?", "string"),
                ("size?", "AvatarSize"),
                ("subtitle?", "string"),
            ],
        ),
        (
            "avatar_group",
            vec![
                ("avatars", "AvatarConfig[]"),
                ("size?", "AvatarSize"),
                ("max?", "number"),
            ],
        ),
        (
            "progress_bar",
            vec![
                ("value", "number"),
                ("label?", "string"),
                ("color?", "SemColor"),
                ("detail?", "string"),
            ],
        ),
        (
            "empty_state",
            vec![
                ("title", "string"),
                ("body?", "string"),
                ("action?", "EmptyStateAction"),
                ("icon?", "string"),
            ],
        ),
        (
            "icon",
            vec![
                ("name", "string"),
                ("size?", "IconSize"),
                ("color?", "SemColor"),
            ],
        ),
        (
            "chart",
            vec![
                ("kind", "ChartKind"),
                ("title?", "string"),
                ("height?", "number"),
                ("x_label?", "string"),
                ("y_label?", "string"),
                ("orientation?", "ChartOrientation"),
                ("data?", "ChartPoint[]"),
                ("series?", "ChartSeries[]"),
            ],
        ),
        ("role_map", vec![("title?", "string")]),
    ];

    for (i, (tag, fields)) in components.iter().enumerate() {
        out.push_str("  | { type: \"");
        out.push_str(tag);
        out.push('"');
        for (name, ts_type) in fields {
            out.push_str("; ");
            out.push_str(name);
            out.push_str(": ");
            out.push_str(ts_type);
        }
        out.push_str(" }");
        if i < components.len() - 1 {
            out.push('\n');
        }
    }
    out.push_str(";\n\n");

    // Freshness types
    emit_interface(
        &mut out,
        "SourceOfTruth",
        &[("label", "string"), ("href?", "string")],
    );
    emit_interface(
        &mut out,
        "RefreshStep",
        &[
            ("run?", "string"),
            ("prompt?", "string"),
            ("review?", "string"),
        ],
    );
    emit_interface(
        &mut out,
        "RefreshConfig",
        &[("mode?", "RefreshMode"), ("steps?", "RefreshStep[]")],
    );
    emit_interface(
        &mut out,
        "Freshness",
        &[
            ("updated?", "string"),
            ("review_every?", "string"),
            ("owner?", "string"),
            ("sources_of_truth?", "(string | SourceOfTruth)[]"),
            ("expires?", "string"),
            ("refresh?", "string | RefreshConfig"),
        ],
    );
    emit_interface(
        &mut out,
        "Reference",
        &[("url", "string"), ("note?", "string")],
    );

    // Nav / Site config
    emit_interface(
        &mut out,
        "NavLink",
        &[
            ("label", "string"),
            ("href?", "string"),
            ("children?", "NavLink[]"),
            ("personas?", "string[]"),
            ("collapsed?", "boolean"),
        ],
    );
    emit_interface(
        &mut out,
        "Voice",
        &[
            ("tone?", "string"),
            ("reading_level?", "string"),
            (
                "terminology?",
                "{ prefer?: Record<string, string>; avoid?: string[] }",
            ),
        ],
    );
    emit_interface(
        &mut out,
        "Role",
        &[
            ("id", "string"),
            ("label", "string"),
            ("description?", "string"),
            ("icon?", "string"),
            ("href?", "string"),
        ],
    );
    emit_interface(
        &mut out,
        "DriftRepo",
        &[("prefix", "string"), ("local?", "string")],
    );
    emit_interface(&mut out, "DriftConfig", &[("repos", "DriftRepo[]")]);

    // Page
    out.push_str("export interface Page {\n");
    out.push_str("  title: string;\n");
    out.push_str("  shell: Shell;\n");
    out.push_str("  eyebrow?: string;\n");
    out.push_str("  subtitle?: string;\n");
    out.push_str("  components?: Component[];\n");
    out.push_str("  slides?: Slide[];\n");
    out.push_str("  unlisted?: boolean;\n");
    out.push_str("  texture?: Texture;\n");
    out.push_str("  glow?: Glow;\n");
    out.push_str("  print_flow?: PrintFlow;\n");
    out.push_str("  search_terms?: string[];\n");
    out.push_str("  freshness?: \"never\" | Freshness;\n");
    out.push_str("  owner?: string;\n");
    out.push_str("  references?: Reference[];\n");
    out.push_str("  personas?: string[];\n");
    out.push_str("  archived?: boolean;\n");
    out.push_str("  draft?: boolean;\n");
    out.push_str("  nav_layout?: NavLayout;\n");
    out.push_str("  nav?: NavLink[];\n");
    out.push_str("}\n\n");

    // SiteConfig
    out.push_str("export interface SiteConfig {\n");
    out.push_str("  name: string;\n");
    out.push_str("  theme?: string;\n");
    out.push_str("  colors?: Record<string, string>;\n");
    out.push_str("  nav?: NavLink[];\n");
    out.push_str("  favicon?: string | { svg?: string; png?: string; ico?: string; apple_touch_icon?: string };\n");
    out.push_str("  logo?: string | { src: string; height?: string; alt?: string };\n");
    out.push_str("  view_source?: boolean;\n");
    out.push_str("  texture?: Texture;\n");
    out.push_str("  glow?: Glow;\n");
    out.push_str("  nav_layout?: NavLayout;\n");
    out.push_str("  mode?: Mode;\n");
    out.push_str("  description?: string;\n");
    out.push_str("  url?: string;\n");
    out.push_str("  edit_url?: string;\n");
    out.push_str("  og_image?: string;\n");
    out.push_str("  voice?: Voice;\n");
    out.push_str("  roles?: Role[];\n");
    out.push_str("  drift?: DriftConfig;\n");
    out.push_str("}\n\n");

    // ValidationError
    emit_interface(
        &mut out,
        "ValidationError",
        &[
            ("file", "string"),
            ("path", "string"),
            ("error_type", "string"),
            ("message", "string"),
            ("suggestion?", "string"),
        ],
    );

    // Annotation
    emit_interface(
        &mut out,
        "Annotation",
        &[
            ("id", "string"),
            ("text", "string"),
            ("author", "string"),
            ("section?", "string"),
            ("added", "string"),
            ("status", "AnnotationStatus"),
            ("source", "AnnotationSource"),
        ],
    );

    out
}

fn emit_enum(out: &mut String, name: &str, variants: &[&str]) {
    out.push_str("export type ");
    out.push_str(name);
    out.push_str(" = ");
    for (i, v) in variants.iter().enumerate() {
        if i > 0 {
            out.push_str(" | ");
        }
        out.push('"');
        out.push_str(v);
        out.push('"');
    }
    out.push_str(";\n\n");
}

fn emit_interface(out: &mut String, name: &str, fields: &[(&str, &str)]) {
    out.push_str("export interface ");
    out.push_str(name);
    out.push_str(" {\n");
    for (name, ts_type) in fields {
        if let Some(stripped) = name.strip_suffix('?') {
            out.push_str("  ");
            out.push_str(stripped);
            out.push_str("?: ");
        } else {
            out.push_str("  ");
            out.push_str(name);
            out.push_str(": ");
        }
        out.push_str(ts_type);
        out.push_str(";\n");
    }
    out.push_str("}\n\n");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn typescript_output_contains_key_types() {
        let ts = generate_typescript();
        assert!(ts.contains("export type Shell ="));
        assert!(ts.contains("export interface Page {"));
        assert!(ts.contains("export interface SiteConfig {"));
        assert!(ts.contains("export type Component ="));
        assert!(ts.contains("export interface ValidationError {"));
        assert!(ts.contains("{ type: \"header\""));
        assert!(ts.contains("{ type: \"chart\""));
        assert!(ts.contains("{ type: \"role_map\""));
    }
}
